### ISSUE TITLE
Using findAllEventsInNamedCalendar when there are calendars with duplicated name

### ISSUE THREAD

**Issue by chymtt** [EddyVerbruggen/Calendar-PhoneGap-Plugin#114]
I need to list all events in all calendars in iOS so i used findAllEventsInNamedCalendar, but it seems this only returns the events in the first calendar with the provided name. Is there anyway to overcome this limitation?

**Comment by EddyVerbruggen** [comment]
There is no workaround, you will indeed get the events in the first calendar with that name. I'm curious how you managed to have two calendars with the same name. Perhaps one is local, the other in iCloud, but the plugin itself doesn't allow creating two calendars with the same name.

It's possible to change the code to support multiple calendars with the same name for `findAllEventsInNamedCalendar` but I don't have a useful testcase for it and it seems like an edge case to me.

@everyone: please reopen if you feel this is something this plugin should support in the future. I'd love to receive a PR extending the iOS `findAllEventsInNamedCalendar` implementation is that case.

**Comment by samedii** [comment]
@EddyVerbruggen This works in the other implementation since we use id for all this stuff. Also having multiple calendars with the same name happens all the time in our production environment (all of them are called "Calendar")

**Comment by aklt** [comment]
We have also run into different calendars being named "Calendar" and I have just opened related issue #433 about being able to use the `findEventWithOptions` method to read events from calendars with the same name.
