### ISSUE TITLE
FindEvent: No error or response after running the function (Android 4.2.2)

### ISSUE THREAD

**Issue by w3irdo** [EddyVerbruggen/Calendar-PhoneGap-Plugin#118]
Hi, I am using Android 4.2.2. It is working with createEvent but not findEvent. There is no error or response (success,error) after running this function. Any reason?

.... all the variables......

 window.plugins.calendar.findEvent(title,location,notes,startDate,endDate,success,error);            	
            	 
            	var success = function(message) {             		

            		alert("findCalendar: success - ");
            		
            	}; 
            	
            	var error = function(message) {
            		alert(" .Unable to find calendar. Try again."); 
            		
            	};

**Comment by EddyVerbruggen** [comment]
Hi, the `findEvent` function doesn't have the best error handling in the world, so you may have passed something invalid to the plugin. You could attach the device to your computer and run `adb logcat` to see if any error was logged. Feel free to share more of your code so I can take a more thorough look.

**Comment by w3irdo** [comment]
Hi, i dont know what is the problem. To solve this, I have to declare the function outside the function itself. If i do this "var success = function(message) {" as above, there will not be any response

eg.
function addCalendar(message) {
window.plugins.calendar.createEventWithOptions(title,location,notes,startDate,endDate,calOptions,onAddCalendarSuccess,onAddCalendarError);             	  
}
            
            function onAddCalendarSuccess(message) {
            	alert("Success addCalendar");
  
	    	}
            
            function onAddCalendarError(message) {
            	alert("error addCalendar");
            	
	    	}
