### ISSUE TITLE
Apple rejection My App running calendar

### ISSUE THREAD

**Issue by voltea** [EddyVerbruggen/Calendar-PhoneGap-Plugin#119]
Dear,

I have a problem, I'm taking your calendar, it works perfectly on all devices but 5s iphone, iphone 6 iphone 6 plus the application does not work in the emulator have the following alert:

HRead WARNING: ['Calendar'] took '272.427979' ms. Plugin Should use a background thread.

But the application works well only on real devices does not work.

Could help please.

Thank You

**Comment by EddyVerbruggen** [comment]
Hi, what do you mean by 'Apple rejection'? It's not clear to me...

Does it work on the simulator, device, or none of those?

Also, that warning can safely be ignored.

**Comment by voltea** [comment]
Iphone 5s simulator works, but 5s physical device does not work

I can send the draft for review?

Thank You

**Comment by samedii** [comment]
@voltea  On the simulator the plugin isn't even used (because there is no calendar on the simulator).

If you care about that warning and want to fix it (because it locks the app for a short while) you can take a look at how I do it in [my branch](https://github.com/samedii/Calendar-PhoneGap-Plugin) (which is not done yet).

**Comment by voltea** [comment]
Samedii,

This is my code for call calendar.

 var calOptions = window.plugins.calendar.getCalendarOptions(); // grab the defaults
  calOptions.firstReminderMinutes = 0; // default is 60, pass in null for no reminder (alarm)
  calOptions.secondReminderMinutes = 10;

  
 
  calOptions.recurrence = "daily"; // supported are: daily, weekly, monthly, yearly
  calOptions.recurrenceEndDate = new Date(duracionAnio,duracionMes,duracionDia,localStorage['hora'+j],minutosMasUno,0,0,0); // leave null to add events into infinity and beyond
  

  
  window.plugins.calendar.createEventWithOptions(title,location,notes,startDate,endDate,calOptions,success,error);

**Comment by voltea** [comment]
Dear,

i solved the problem with change the phongeap version.

3.2 ----> 3.6.3

Thx 

See you!
