### ISSUE TITLE
Ionic build ios failed

### ISSUE THREAD

**Issue by tuananh** [EddyVerbruggen/Calendar-PhoneGap-Plugin#121]
I did

    cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
    ionic build ios

and I got this error. Do I have to manually copy these files over ?

    clang: error: no such file or directory: '/Users/username/src/myApp/platforms/ios/myApp/Plugins/nl.x-services.plugins.calendar/Calendar.m'

**Comment by EddyVerbruggen** [comment]
Hi, you shouldn't have to copy those files manually - can you try running `cordova prepare` after that first command?

**Comment by tuananh** [comment]
@EddyVerbruggen same error. could this be Ionic framework specific problem!?

**Comment by EddyVerbruggen** [comment]
I have been using plugins with Ionic without much trouble so I don't think so. Also, I just tried it with the latest Ionic CLI and it worked fine with the following commands. I think you're best off creating a new project in the same way and copying over your www folder afterwards.

```
ionic start ionictest
cd ionictest/
ionic setup sass
ionic platform add ios
ionic plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin
ionic build ios
..
..
** BUILD SUCCEEDED **
```

**Comment by tuananh** [comment]
Thank you. Lemme try creating project again.

**Comment by mnewmedia** [comment]
close this..
