### ISSUE TITLE
createEventWithOptions ios 8.1.1 (iphone 6) CRASH

### ISSUE THREAD

**Issue by voltea** [EddyVerbruggen/Calendar-PhoneGap-Plugin#123]
Hi Guys,

i have problem, when execute createEventWithOptions in ios 8.1.1 in iphone 6.

My App Crash with message: Thread 1: EXC_BAD_ACCESS(code=1, address=0x6b000003a20261)

Help plis

Thx

see you!

**Comment by w3irdo** [comment]
wish to know too. mine is working in 8.0.1. have not tried in 8.1.1

**Comment by voltea** [comment]
The problem is that it works on ios 8.1.1 on all devices, with the exception iphone 5s, 6 and iphone iphone 6 plus.

Could send my project so you can help me please.

Thank You

**Comment by EddyVerbruggen** [comment]
@voltea If you project reproduces the error then please go ahead and send it over to eddyverbruggen at gmail dot com, thanks!

**Comment by voltea** [comment]
solved problem with change the phonegap version.

3.2 ---- > 3.6.3

Thx!

**Comment by EddyVerbruggen** [comment]
:+1: 
Thanks for letting me know!

**Comment by qanuj** [comment]
This is happening again in iOS 8.1.1 but with cordova v5.3.3  any ideas ?
