### ISSUE TITLE
createEventWithOptions - the success response from android and ios is different!

### ISSUE THREAD

**Issue by w3irdo** [EddyVerbruggen/Calendar-PhoneGap-Plugin#124]
FYI

createEventWithOptions - the success response from android and ios is different!

for android, the success returns message "true"
for ios, the success returns message "OK"

Wasted some time to debug this, which I feel should not be programmed this way. I do not have an ios on hand so it is difficult to troubleshoot. Hope future updates be consistent.

**Comment by EddyVerbruggen** [comment]
Although I generally agree with your feedback I do wonder why you check the message in the first place. The fact that the success callback is invoked should suffice. Nowhere in the docs does it tell you to check for a specific message.

**Comment by EddyVerbruggen** [comment]
Done

**Comment by w3irdo** [comment]
Some devices failed to add event even on success respond. I have to check the message then. Thanks for The updates
