### ISSUE TITLE
Android : how to delete all events in the calendar created by my app

### ISSUE THREAD

**Issue by sreejith-m-sreedharan1987** [EddyVerbruggen/Calendar-PhoneGap-Plugin#125]
Hi,
I want to delete all events in the device calendar created by my application. 
I tried deleteEvent() but it is deleting events only if the matched events count = 1. If multiple events are matched, it is not deleting those events eventhough it enters in the success callback.
 var startDate = new Date(1970,1,1,0,0,0,0,0);
 var endDate = new Date(2050,1,1,0,0,0,0,0);

 Calendar.deleteEvent(null,null,null,startDate,endDate,function(msg){
                                    if(success) success();
                                },function(err){
                                    if(error) error();
                                });

I need a quick help, 
Kindly show me a solution.

**Comment by EddyVerbruggen** [comment]
Hmm, the plugin doesn't allow this because your code would wipe the entire calendar of the user (not only stuff added by this plugin), that's probably not what you want.

You could do a find which returns multiple items and delete those one by one..

**Comment by sreejith-m-sreedharan1987** [comment]
Yes you are right, I did it too, but it returns all events in the calendar including the events not related to my application, It took almost 10 seconds to load all searched events. I want to know if there is any method to find the events created by application only.

**Comment by EddyVerbruggen** [comment]
It depends. If you always use the same description or location you can pass that into the find method as a filter to restrict your result. There is no other way.

**Comment by sreejith-m-sreedharan1987** [comment]
Can we search title with patterns? for e.g if my event titles are prepended by 'My App name : ', can we retrieve all the events with title text beginning with 'My App name :'  in a faster way? All other will vary.

**Comment by EddyVerbruggen** [comment]
Not at the moment, it's a nice feature request though.

**Comment by sreejith-m-sreedharan1987** [comment]
Hi Eddy,
i have created a prefix and prepended to title text , used title.startsWith(prefix) to identify my app's events and used 'continue' to skip that loop if not. Now it works much faster and retrieves events within a second. I think it would be faster if implemented a filtration in the calendar event retrieval query itself.

**Comment by EddyVerbruggen** [comment]
@sreejith-m-sreedharan1987 you can now search event titles with a prefix as you suggested.

Thanks,
Eddy
