### ISSUE TITLE
ios app crashes while finding an event with location containing single quotes 

### ISSUE THREAD

**Issue by sreejith-m-sreedharan1987** [EddyVerbruggen/Calendar-PhoneGap-Plugin#131]
This issue occurs in all versions of ios devices.  Create an event in calendar with location or title containing a single quote, the createEventInNamedCalendar() succeeds and creates an event in calendar with that single quote.

But, the problem occurs when finding that event using findAllEventsInNamedCalendar().

The app crashes immediately upon finding such entries. 
I went through the code and i could see that line number 214 to 231 in Calendar.m causes this issue.
You have written In line number 218,

 [predicateStrings addObject:[NSString stringWithFormat:@"location == '%@'", location]];

and then in line number 229,

 if (predicateString.length > 0) {
    matches = [NSPredicate predicateWithFormat:predicateString];

the 'matches' resolves to nil when a location name with a single quote is passed. And the app quits suddenly throwing an error.

This is because the quotes are not properly escaped in the predicate string.

Please fix this issue at the earliest since it will cause the sudden death of the app on executing the above code.

Thanks for creating and maintaining this useful repository.

**Comment by EddyVerbruggen** [comment]
Hi, this has been solved in the meanwhile. See this screenshot. Thanks for reporting!

![img_3344](https://cloud.githubusercontent.com/assets/1426370/6653235/b610b0d0-ca89-11e4-947e-8d7b9865a056.PNG)

**Comment by EddyVerbruggen** [comment]
BTW, I just found (and fixed) a similar problem for the `findEvent` function. Single quotes in title, location and notes would lead to errors.
