### ISSUE TITLE
Unable to run using Chrome ("phonegap serve" console command)

### ISSUE THREAD

**Issue by stimpy77** [EddyVerbruggen/Calendar-PhoneGap-Plugin#133]
I get this error when the script gets retrieved. I have updated the global install of Cordova and also removed and re-added the calendar plugin reference, no change.

Error: ENOENT, no such file or directory 'C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\res\middleware\cordova\3.6.4\android\plugins\Calendar.js' at Object.fs.openSync (fs.js:439:18) at Object.fs.readFileSync (fs.js:290:15) at Object.handle (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\plugins.js:28:27) at next (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15) at Object.handle (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova_plugins.js:30:13) at next (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15) at Object.handle (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:33:13) at next (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15) at resume (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:65:7) at SendStream.error (C:\Users\stimpy77\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:80:37)

**Comment by rmcnulty** [comment]
You must use a device ( ios or android ) as a browser does not have a calendar

**Comment by stimpy77** [comment]
Does too. http://www.html5tutorial.info/html5-date.php

**Comment by stimpy77** [comment]
Mock one, so that JS can continue.

**Comment by EddyVerbruggen** [comment]
@stimpy77 Indeed, mock the Calendar or use a device/emulator.
