### ISSUE TITLE
listEventsInRange problems

### ISSUE THREAD

**Issue by raoulcimpean** [EddyVerbruggen/Calendar-PhoneGap-Plugin#134]
I run application on a galaxy s2 with andorid 4.2.2
I cand add a new event in calendar , but if i want to list all events , it doesen`t work.
This is my code: $scope.events = window.plugins.calendar.listEventsInRange(startDate, endDate, success, error);

Can you help me?
THX

**Comment by EddyVerbruggen** [comment]
Hi, the result of the `listEventsInRange` function is passed to your js code in the success handler, you can't assign it directly.

**Comment by raoulcimpean** [comment]
THX

**Comment by raoulcimpean** [comment]
I`m new on this , and it doesen`t work .
 window.plugins.calendar.listEventsInRange(startDate, endDate, success, error).then(function (result) {
                $scope.events = result;
                alert(success);
            }, function (error) {
                console.log("error");
            });
can you tell me please what is wrong?

**Comment by raoulcimpean** [comment]
I solved it. thank you
