### ISSUE TITLE
Event not showing up in calendar | Android 4.3

### ISSUE THREAD

**Issue by msalman** [EddyVerbruggen/Calendar-PhoneGap-Plugin#135]
Hi Eddy,

I am trying to add the event, it is working fine in IOS but in android I do get the success message but when i go the calendar it doesn't show me any event, this is just happening in android. Below is my code.

```javascript
var startDate = new Date(2015,2,18,18,30,0,0,0);
var endDate = new Date(2015,2,18,19,30,0,0,0);
var title = "My nice event";
var location = "Home";
var notes = "Some notes about this event."
var success = function(message) { alert("Success: " + JSON.stringify(message)); };
var error = function(message) { alert("Error: " + message); };
var calOptions = window.plugins.calendar.getCalendarOptions();
window.plugins.calendar.createEventWithOptions (title,location,notes,startDate,endDate,calOptions,success,error);
```

I found this link https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/41and I change the code in Calendar.java line number 231 to below.

```
getCalendarAccessor().createEvent(
          null,
          argObject.getString("title"),
          argObject.getLong("startTime"),
          argObject.getLong("endTime"),
          argObject.isNull("notes") ? null : argObject.getString("notes"),
          argObject.isNull("location") ? null : argObject.getString("location"),
          null, /*change by me*/
          null,/*change by me*/
          null,/*change by me*/
          null/*change by me*/
      );
```

**Comment by EddyVerbruggen** [comment]
Hi, sorry to ask the obvious thing, but did you check your calendar at feb 18th or march 18th? Those JS dates confuse the hell out of people :)

**Comment by msalman** [comment]
I am really sorry to tell you that I forgot that months will start from 0 so December means 11 and not 12 .... my bad, extremely sorry for that :)

**Comment by EddyVerbruggen** [comment]
Lol, just glad my gut feeling was correct. :+1: 

Thanks,
Eddy
