### ISSUE TITLE
createEventWithOptions recurrence problem

### ISSUE THREAD

**Issue by raoulcimpean** [EddyVerbruggen/Calendar-PhoneGap-Plugin#138]
On android when i add an event with options , the recurrence is monthly or daily or weekly, i have recurrenceEndDate null , but on my calendar i have the event only for 2 month. If a`m adding again same event with same data ,  it goes for 4 months ... 6 months etc. 
With yearly doesen`t work at all. It goes just one time in calendar. 
        var success = function (message) {
            alert("Success: ");
        }
        var error = function (message) {
            alert("Error: " + message);
        };
        var calOptions = window.plugins.calendar.getCalendarOptions();
        calOptions.recurrence = "monthly";
        //calOptions.recurrenceEndDate = new Date(2016, 01, 28, 16, 23, 0, 0, 0);
        var title = "title";
        var location = "Moon";
        var notes = "HAAHa";
        var startDate = new Date(2015, 01, 28, 16, 23, 0, 0, 0);
        var endDate = new Date(2015, 01, 28, 17, 23, 0, 0, 0);
        window.plugins.calendar.createEventWithOptions(title, location, notes, startDate, endDate, calOptions, success, error);

**Comment by raoulcimpean** [comment]
i run this code onIOS and it works perfectly! I don`t know which is the problem on android.

**Comment by EddyVerbruggen** [comment]
This should be fixed with the 4.3.0 version I just released. Please test and reopen if there is a problem.

Thanks,
Eddy
