### ISSUE TITLE
Add calendar property to returned event object

### ISSUE THREAD

**Issue by danicastanos** [EddyVerbruggen/Calendar-PhoneGap-Plugin#141]
When retrieving events with findEvent method, it would be very nice to have calendar name or calendar id assoc to the item. It's only one code line:

From:
```objectivec
NSMutableDictionary *entry = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                                  event.title, @"title",
                                  [df stringFromDate:event.startDate], @"startDate",
                                  [df stringFromDate:event.endDate], @"endDate",
                                  nil];
```
To:
```objectivec
NSMutableDictionary *entry = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                                  event.title, @"title",
                                  [df stringFromDate:event.startDate], @"startDate",
                                  [df stringFromDate:event.endDate], @"endDate",
                                  event.calendar.title, @"calendar",
                                  nil];
```

**Comment by EddyVerbruggen** [comment]
Thanks, I just pushed this change.

**Comment by danicastanos** [comment]
Great!!! Thanks!

**Comment by danicastanos** [comment]
Hi Eddy, wouldn't it be nice to have Android part returning the same object structure and add also calendar name?

Thanks!

**Comment by EddyVerbruggen** [comment]
Absolutely - if you have the time, can you perhaps be so kind to make it as easy for me as the change above? :)

**Comment by samedii** [comment]
You could take code from my fork for this is you want

**Comment by EddyVerbruggen** [comment]
Looks like this is the LoC to use: https://github.com/Bramstang/Calendar-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java#L458

Thanks @samedii

**Comment by samedii** [comment]
@EddyVerbruggen  Haha, ye if you want the entire calendar then I think that is in the commit history (we later decided it was a bad idea to send the entire calendar with every event)
