### ISSUE TITLE
openCalendar with date parameter opens at current date on iOS

### ISSUE THREAD

**Issue by QuickCRM** [EddyVerbruggen/Calendar-PhoneGap-Plugin#143]
Hi,

The first time openCalendar is called with a date parameter on iOS, it opens the calendar at current date.
Now, if we call openCalendar again after that, it opens correctly the calendar at the date passed as parameter.

Thanks for this great plug-in.

**Comment by EddyVerbruggen** [comment]
Hmm interesting find. Which iOS version did you notice this on?

**Comment by QuickCRM** [comment]
That's on 8.1.

**Comment by EddyVerbruggen** [comment]
I see what you mean, but it depends on how you closed the calendar app the previous time. If you were in the view where you only see the dates for one month then even the first time the calendar app is opened on the correct date. However if you were in the mode where you see the entire year then the first launch will zoom in on the current month and the second time it loads the correct date.

This sounds like an iOS bug to me. Either way I can't do much more than passing the correct date to the app via the `calshow:<date>` URL scheme.
