### ISSUE TITLE
IOS not responding no errors etc..

### ISSUE THREAD

**Issue by GSD-Automatisering** [EddyVerbruggen/Calendar-PhoneGap-Plugin#144]
Hello Eddy,
i have a strange problem with intergration in IOS on android everything works as intend 
i have the following code:

in my webpage

    <script src="js/Cordova.js"></script>
    <script src="js/Calendar.js"></script>

    function AddCalendarIOS(_startDate, _endDate, _title, _location, _notes) {

    //cDate is a function that converts a string date to a valid JS Date Object.

    var startDate = cDate(_startDate, true);
    var endDate = cDate(_endDate, true);

    var title = _title;
    var location = _location;
    var notes = _notes;

    var success = function (message) {
    };

    var error = function (message) {
    };

    try {

        var cal = window.plugins.calendar;
        var calendarName = 'MyCal';

        var options = cal.getCreateCalendarOptions();
        options.calendarName = calendarName;
        options.calendarColor = "#87B64A"; // passing null make iOS pick a color for you

        cal.createCalendar(options, success, error);
        cal.deleteCalendar(calendarName, success, error);
        cal.createEventInNamedCalendar(title, location, notes, startDate, endDate, calendarName, success, error);
        cal.findAllEventsInNamedCalendar(calendarName, success, error);
    }
    catch (ex) {
        alert(ex);
    }
    }

i dont get any response methods has been regonized but i dont see any items in the IOS calendar.
hope ya can help me Kind Regards Stefan,

**Comment by EddyVerbruggen** [comment]
Stefan emailed me personally, all ok now.

**Comment by GSD-Automatisering** [comment]
No its not :P new issue
