### ISSUE TITLE
IOS not responding no errors etc..

### ISSUE THREAD

**Issue by GSD-Automatisering** [EddyVerbruggen/Calendar-PhoneGap-Plugin#145]
Hello Eddy,
i have a strange problem with intergration in IOS on android everything works as intend 
i have the following code:

in my webpage

<script src="js/Cordova.js"></script>
<script src="js/Calendar.js"></script>

function AddCalendarIOS(_startDate, _endDate, _title, _location, _notes) {

//cDate is a function that converts a string date to a valid JS Date Object.

var startDate = cDate(_startDate, true);
var endDate = cDate(_endDate, true);

var title = _title;
var location = _location;
var notes = _notes;

var success = function (message) {
};

var error = function (message) {
};

try {

    var cal = window.plugins.calendar;
    var calendarName = 'MyCal';

    var options = cal.getCreateCalendarOptions();
    options.calendarName = calendarName;
    options.calendarColor = "#87B64A"; // passing null make iOS pick a color for you

    cal.createCalendar(options, success, error);
    cal.deleteCalendar(calendarName, success, error);
    cal.createEventInNamedCalendar(title, location, notes, startDate, endDate, calendarName, success, error);
    cal.findAllEventsInNamedCalendar(calendarName, success, error);
}
catch (ex) {
    alert(ex);
}
}
i dont get any response methods has been regonized but i dont see any items in the IOS calendar.
hope ya can help me Kind Regards Stefan,

**Comment by EddyVerbruggen** [comment]
Hi Stefan,

Did you try adding a body to the `success` and `error` functions? These should be invoked after calling the plugin.

```js
var error = function (message) {
  alert(JSON.stringify(message));
};
```

**Comment by GSD-Automatisering** [comment]
Yes wont trigger

**Comment by EddyVerbruggen** [comment]
Can you please send me the sourcecode to reproduce this problem?

**Comment by GSD-Automatisering** [comment]
its html5 not xcode

**Comment by samedii** [comment]
Still need XCode to build for iOS and so you have to have an XCode project

**Comment by GSD-Automatisering** [comment]
True but you can also Build at Adobe

**Comment by EddyVerbruggen** [comment]
A PhoneGap Build compatible html5 project is fine as well. Please send it to me so I can reproduce the problem.

**Comment by GSD-Automatisering** [comment]
Well eddy its an Redirect to our server so i can send you but its nothing than a index.html that redirects to a server with the JQM html5 application :P

**Comment by EddyVerbruggen** [comment]
I need your code to be able to reproduce it. PM me.

**Comment by GSD-Automatisering** [comment]
pmed you to gmail

**Comment by ikem06** [comment]
I'm using Phonegap Build and having the same issue. I can only create calendars.
Events doesnt have any response at all
