### ISSUE TITLE
IOS Delete repeatly event - problem resolved

### ISSUE THREAD

**Issue by raoulcimpean** [EddyVerbruggen/Calendar-PhoneGap-Plugin#150]
I found which was the problem with repeatly events on IOS. If you delete an repeatly event and the last event remains .. you must change EKSpanThisEvent with EKSpanFutureEvents.

 for (EKEvent * event in matchingEvents) {
    [self.eventStore removeEvent:event span:EKSpanFutureEvents  error:&error];
  }

I have a problem with GMT also. I fixed it.

NSTimeInterval _startInterval = [startTime doubleValue] / 1000; // strip millis
    NSTimeInterval timeZoneOffset = [[NSTimeZone defaultTimeZone] secondsFromGMT];
    _startInterval -= timeZoneOffset;
    NSDate *myStartDate = [NSDate dateWithTimeIntervalSince1970:_startInterval];
    
    NSTimeInterval _endInterval = [endTime doubleValue] / 1000; // strip millis
    _endInterval -= timeZoneOffset;
    NSDate *myEndDate = [NSDate dateWithTimeIntervalSince1970:_endInterval];
    
    NSArray *matchingEvents = [self findEKEventsWithTitle:title location:location notes:notes startDate:myStartDate endDate:myEndDate calendar:calendar];

**Comment by EddyVerbruggen** [comment]
Thanks for letting me know, I'll test these locally and change the code if necessary.
