### ISSUE TITLE
Not working on LG G3 (Android 5)

### ISSUE THREAD

**Issue by Defcon0** [EddyVerbruggen/Calendar-PhoneGap-Plugin#154]
Hello,

unfortunately, the method createEventInteractively doesn't work on the LG G3. To put it simple, nothing happens when running the method.

Do you have any idea, why this is? If you need more info, no problem.

Bye!

**Comment by Defcon0** [comment]
Please ignore the issue. It was my fault, just a typo :(

**Comment by EddyVerbruggen** [comment]
No worries m8
