### ISSUE TITLE
Event values must include a calendar_id

### ISSUE THREAD

**Issue by zenmiami** [EddyVerbruggen/Calendar-PhoneGap-Plugin#157]
cordova -v = 4.3.0
android app, worked in previous version of cordova but building in app studio, gradle, etc, i get the following error in the log

 W/System.err﹕ Exception: Event values must include a calendar_id
 W/PluginManager﹕ THREAD WARNING: exec() call to Calendar.createEventWithOptions blocked the main thread for 74ms. Plugin should use CordovaInterface.getThreadPool().
 W/CordovaPlugin﹕ Attempted to send a second callback for ID: Calendar102056296
    Result was: "Invalid action"

your enlightenment is needed.
robert

**Comment by EddyVerbruggen** [comment]
Oh dear, that's caused by the PR in #153. I just fixes it in version 4.3.1.

Many thanks for reporting this issue!
Eddy

**Comment by junedlanja** [comment]
i fixed it by changing 
 argOptionsObject.isNull("calendarId") ? null : argOptionsObject.getInt("calendarId")
to 
 argOptionsObject.isNull("calendarId") ? 1: argOptionsObject.getInt("calendarId")

Another option is using createEventWithOptions and setting calender_id in option.

Brother you should provide better documentation for it. 

Thanks  Eddy Verbruggen for this plugin...

**Comment by EddyVerbruggen** [comment]
@junedlanja that's the exact fix I created for 4.3.1.

**Comment by junedlanja** [comment]
@EddyVerbruggen  sorry i got it later ...eddy thanks for your good work
