### ISSUE TITLE
Fix docs regarding Android calendarId

### ISSUE THREAD

**Issue by brabeji** [EddyVerbruggen/Calendar-PhoneGap-Plugin#159]
calendarId option example should be added into docs. On Android imho you should always set calendarId because for example on my device there is no calendar with default id of 1. Since there is no error when creating event in nonexistent calendar and event is simply not created, this is extremely confusing and took me a while to debug.

**Comment by EddyVerbruggen** [comment]
Very good idea. Could you please send me a PR with the revised doc?
