### ISSUE TITLE
Can't delete a calendar entry

### ISSUE THREAD

**Issue by gkustas** [EddyVerbruggen/Calendar-PhoneGap-Plugin#166]
I'm new to this plugin, but I have read through all of the issues in this forum.

I have successfully created a calendar event in android (4.4, HTC One). 

I am now trying to delete it and I am unsuccessful. The success handler is called, but the return value is "false" and the event is not deleted from the calendar. I am sending a valid start date, end date and title. Does anything else need to be sent? Location and notes are empty strings. Here is my code:

window.plugins.calendar.deleteEvent(
			custom.title,
			custom.location,
			custom.notes,
			new Date(custom.startDate),
			new Date(custom.endDate),
			function (status) {
				console.log("deleted reservation from calendar successfully. Status=" + status);
			},
			function(status) {
				console.log("Error deleting reservation from calendar. Status=" + status);
			});

**Comment by EddyVerbruggen** [comment]
Are you 100% sure the startdate and enddate passed are exactly the same as the ones you used to create the event? FYI - on Android the notes are ignored when deleting an event.

**Comment by EddyVerbruggen** [comment]
By the way, which version of the plugin are you using? Last month there was  a bugfix for deleting events on Android, see #147.

**Comment by gkustas** [comment]
Ok - I just downloaded the latest (4.3.3) and the events are deleting. Thank you!
