### ISSUE TITLE
Null URL in CreateEvent

### ISSUE THREAD

**Issue by Bronwenist** [EddyVerbruggen/Calendar-PhoneGap-Plugin#168]
I had problems calling `createEvent(..)` in iOS.  Basically this line below

    window.plugins.calendar.createEvent(title,eventLocation,notes,startDate,endDate,success,error);

gave an error  in Calendar.m at line 387:

      NSURL* myUrl = [NSURL URLWithString:url];

Replacing it with the code from `createEventInteractively()` which checked for NULL fixed the problem.

**Comment by EddyVerbruggen** [comment]
Thanks - fixed in 4.3.4
