### ISSUE TITLE
Unable to distinguish Add from Cancel in createEventInteractively

### ISSUE THREAD

**Issue by jberlet** [EddyVerbruggen/Calendar-PhoneGap-Plugin#169]
Is it possible to distinguish these actions based on the callback (success or error) return codes or what options/workaround do we have to tell if my user(s) pressed the Cancel button? I need to be able to distinguish these actions as cancelling out of the calendar triggers my app. actions and I don't want it to. Could I add some kind of onClick watch on the Cancel button in JS? I need to use the createEventInteractively() but I need to know if the user cancelled out.

It seems this was answered here:
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/23
but since this time, the CANCEL and SUCCESS seem to always return OnSuccess.
Can this be fixed for Android?

**Comment by EddyVerbruggen** [comment]
See my comment [here](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Calendar.java#L324).. both success and cancel return `0` back to the plugin code, so we can't know.

What you could do as a workaround is do a `findEvent` in the success handler of `createEventInteractively`.
