### ISSUE TITLE
findEvent / IOS

### ISSUE THREAD

**Issue by dschammne** [EddyVerbruggen/Calendar-PhoneGap-Plugin#174]
Hello! 

If I use findEvent in IOS, I get only calendar events from the default device calendar. In Android there are all events between startDate and endDate from all device calendars. Is there a way to get all events from all calendars in IOS?

Thank you and best regards,
Dominik

**Comment by justincolangelo** [comment]
+1

I am not able to get any events to return using `window.plugins.calendar.findEvent(title,eventLocation,notes,startDate,endDate,success,error);`

The success callback returns `[]` each time even though I've added the same event multiple times. This is probably because it doesn't look at the calendar with a custom name.

**Comment by EddyVerbruggen** [comment]
Hi,

You guys are right and I'm thinking about a fix. In the meanwhile, does it help to use the `findAllEventsInNamedCalendar` function for iOS?

**Comment by justincolangelo** [comment]
I attempted to use that method in my application. It returned `[]` like the other one. I am not sure what could be happening. I am using a string variable with my calendar name to create the calendar, and the same variable later to find the events in that calendar.

**Comment by dschammne** [comment]
The problem is in Calendar.m, line 639:
```javascript
EKCalendar* calendar = self.eventStore.defaultCalendarForNewEvents;
```

If you define options, calendar name will be ignored. The plugin only uses the default calendar.

In
```javascript
-(NSArray*)findEKEventsWithTitle
```
at lines 238 and 244 I changed
```javascript
datedEvents = [self.eventStore eventsMatchingPredicate:[eventStore predicateForEventsWithStartDate:startDate endDate:endDate calendars:calendarArray]]; 
```
to
```javascript
datedEvents = [self.eventStore eventsMatchingPredicate:[eventStore predicateForEventsWithStartDate:startDate endDate:endDate calendars:nil]];
```

In my use case I need the results from all calendars. That's why it is a solution for me.

Best regards,
Dominik

**Comment by EddyVerbruggen** [comment]
@dschammne That's OK, if you want to search all calendars :+1: 

Others, I have just pushed a change which allows you to specify a calendarName (or leave empty for default as it is now). See the updated readme, search for `findEventWithOptions`.
