### ISSUE TITLE
2 events with same name only returned once by listEventsInRange()

### ISSUE THREAD

**Issue by Appstractie** [EddyVerbruggen/Calendar-PhoneGap-Plugin#175]
I have 2 events with the same name on a particular day. These events only shows once in the success array on Android. Once I change the name of one of the events, both events appear. 

I use the same event name for example to block some hours of the day for administration. 
I am looking at the Java query part but I'm unsure if I can fix this

Update:
This seems to happen only to recurring events. So I am not sure if the function is down to the listEventsInRange() function or just to not seeing recurring events at all.

**Comment by EddyVerbruggen** [comment]
Let's continue at #156
