### ISSUE TITLE
ClassNotFoundException: nl.xservices.plugins.Calendar

### ISSUE THREAD

**Issue by oBigZee** [EddyVerbruggen/Calendar-PhoneGap-Plugin#176]
Hi,
Can't seem to get this working, been working on this for a little while now. So, I'm using this plugin with ngCordova and Ionic. So, I've installed the plugin using "cordova plugin add", i'm importing ngCordova at the correct spot and injecting the dependency. I've used sample code from here: http://ngcordova.com/docs/plugins/calendar/ and the docs here on GitHub, however it looks like when I deploy to my Nexus 4 to test out the code (command I used for that is "ionic run android"), when I hit the button to add to calender, nothing happens. So, I ran adb logcat and it looks like it's throwing"java.lang.ClassNotFoundException: nl.xservices.plugins.Calendar" 

Here's a screenshot of the adb log: http://i.imgur.com/7F6BE7f.png 

Any idea what I'm doing wrong?

Thanks!

**Comment by EddyVerbruggen** [comment]
Perhaps you need to do a `cordova prepare` after `cordova plugin add ..`?

**Comment by Appstractie** [comment]
In Ionic, I also could not add the plugin as we normally add Cordova plugins. I 
built a way around it:

window.plugins = {};
window.plugins.calendar = new Calendar();

$ionicPlatform.ready(function () {
                  window.plugins.calendar.listEventsInRange(startDate,endDate,success,error);

});

**Comment by oBigZee** [comment]
@EddyVerbruggen cordova prepare fixed the issue. Thank you!

@Appstractie Got it working now, the $ionicPlatform helped. Thank you!
