### ISSUE TITLE
Recurrance every 2 weeks

### ISSUE THREAD

**Issue by rmcnulty** [EddyVerbruggen/Calendar-PhoneGap-Plugin#180]
I was hoping to have recurrance every 2 weeks by day this is not possible with this plugin

e.g. every second monday from a particular date
example vcal rule:
RRULE: FREQ=WEEKLY;INTERVAL=2;BYDAY=MO

**Comment by kanduvisla** [comment]
I noticed in the iOS code, that the interval is a magic number set to '1'. See https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/ios/Calendar.m#L221 for example.

The iOS documentation status that this can be an integer to set the interval: https://developer.apple.com/library/ios/documentation/EventKit/Reference/EKRecurrenceRuleClassRef/index.html#//apple_ref/occ/instp/EKRecurrenceRule/interval

Perhaps this could be an entry point for you. I'm currently running into the same problem where I have to set an interval of 4 weeks / 28 days.

**Comment by EddyVerbruggen** [comment]
Added `recurrenceInterval` (see the readme) to iOS (thanks @kanduvisla for the PR) and Android (by yours truly).

Available in 4.3.7.
