### ISSUE TITLE
unique ID per event for android

### ISSUE THREAD

**Issue by jack-dev** [EddyVerbruggen/Calendar-PhoneGap-Plugin#187]
Why the plugin doesn't include unique ID per event for android, I checked the code and it is possible so I've added it manually and its working fine, but is there any reason why the id is not listed per event?

**Comment by lstone** [comment]
I'd also like to know if this feature will be supported.

**Comment by EddyVerbruggen** [comment]
No reason other than no one asked before. @jack-dev would you mind doing a PR with your changes?

**Comment by lstone** [comment]
Being able to find events via ID for both platforms would be really useful +1.

**Comment by aaronprojects** [comment]
+1

**Comment by wood1master7** [comment]
"Regarding iOS: when passing in the id to search for an event, the findEventWithOptions function will try to match solely against that id. If it's not found it will try to match against the title, etc.

The Android implementation of this plugin currently has no support for finding events by ID. PR's are welcome as I won't be able to do this any time soon."
-Eddy

**Comment by EddyVerbruggen** [comment]
Found a way, Android returns the Event ID as of version 4.3.7.
