### ISSUE TITLE
How to detect 'Cancel' and 'Done' button on method createEventInteractively

### ISSUE THREAD

**Issue by chompunut** [EddyVerbruggen/Calendar-PhoneGap-Plugin#193]
I used 'createEventInteractively' for ask user that they want to create an event on there calendar or not. It will show UI of native calendar to create an event that user can click on Cancel or Done.

The success function just return a message 'OK' matter what user click Cancel or Done.
How I know that user clicked on Cancel or Done button? 
Thanks.

```
var success = function (message) {
     console.log(message);
};
var error = function (message) {
     console.log("Error: " + message);
};
window.plugins.calendar.createEventInteractively(title, eventLocation, notes, startDate, endDate, success, error);
```

**Comment by graphicgeek** [comment]
:+1:

**Comment by kodl** [comment]
:+1:

**Comment by Kim-Andersen** [comment]
:+1:

**Comment by bau720123** [comment]
+1

**Comment by pvelumani** [comment]
+1

**Comment by Romaiin52** [comment]
+1

**Comment by fernandop82** [comment]
Still no solition to this????!!!!

**Comment by EddyVerbruggen** [comment]
@fernandop82 did you try to find one?

**Comment by fernandop82** [comment]
i try but no solution

**Comment by EddyVerbruggen** [comment]
As you can see [in this comment](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/Calendar.java#L637) it's simply not reliable on Android. So create an issue on the Android repo in case that's a problem for you, or do a 'find' when this callback is invoked.
