### ISSUE TITLE
Passing null location causes delete to fail

### ISSUE THREAD

**Issue by movesax** [EddyVerbruggen/Calendar-PhoneGap-Plugin#194]
In your documentation, you say that you can pass null to irrelevant parameters.  However, when I do this on my Nexus 4 running 4.4.4, the delete fails.

The success callback is called, but the message is: false.
This is true for both:
    var startDate = new Date(2014,3,30,21,30,0,0,0);
    var endDate = new Date(2014,3,30,22,30,0,0,0);
    var title = "Testing 123";
    var location = "Homeeee";
    var notes = "Some notes here.";
    var success = function(message) { alert("Success: " + JSON.stringify(message)); };
    var error = function(message) { alert("Error: " + message); };
    window.plugins.calendar.createEvent(title,null,notes,startDate,endDate,success,error);
    window.plugins.calendar.deleteEvent(title,null,notes,startDate,endDate,success,error);

As well as:
    var startDate = new Date(2014,3,30,21,30,0,0,0);
    var endDate = new Date(2014,3,30,22,30,0,0,0);
    var title = "Testing 123";
    var location = "Homeeee";
    var notes = "Some notes here.";
    var success = function(message) { alert("Success: " + JSON.stringify(message)); };
    var error = function(message) { alert("Error: " + message); };
    window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,success,error);
    window.plugins.calendar.deleteEvent(title,null,notes,startDate,endDate,success,error);

This is the code you used in response to a similar question a ways back... only the location parameter was changed.

**Comment by caioreis** [comment]
Same issue here and confirmed. This was driving me crazy.

**Comment by EddyVerbruggen** [comment]
@caioreis I'm not sure what was driving you crazy exactly. Is this is a documentation error? Then please propose a change.

**Comment by caioreis** [comment]
@EddyVerbruggen, sorry about the poor comment. I was creating events with null as location and it was ok. But when you try to delete a batch of events ( I didn't tried just one ) without location it doesn't returns any matches. The docs seems to say that only dates and title are mandatory, but in this case, the location was too.

**Comment by EddyVerbruggen** [comment]
@caioreis Thanks for the explanation. According to the Android code it should be able to deal with a null or empty location. Which device (and Android version) is this?

**Comment by caioreis** [comment]
@EddyVerbruggen, I'm testing on Android 4.4 - Galaxy s5 mini and Android 5.0 Galaxy s6. I didn't tried to use an empty string, just null.

**Comment by EddyVerbruggen** [comment]
Ah, hmm, it seems to read `"null"` (with quotes) in the native code... that's not good.

**Comment by EddyVerbruggen** [comment]
Thanks guys, this has been fixed in 4.3.8.
