### ISSUE TITLE
error cannot call method 'calendar'

### ISSUE THREAD

**Issue by diokudori** [EddyVerbruggen/Calendar-PhoneGap-Plugin#195]
hi buddy , i'm using your plugin for build android application with phonegap . but i can use any of your function to call or add event to native calendar, it's just return error alert . i have search for same issues and try the solution like call the function after onDeviceReady,  but it's still error . can you help me solve this problem?

**Comment by EddyVerbruggen** [comment]
Plz share your project with me if you want anything beyond my guesses ;)
PM at eddyverbruggen at gmail
