### ISSUE TITLE
Creates multiple calendars when passing an array of events to 'createEventWithOptions'

### ISSUE THREAD

**Issue by oktapodi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#196]
I have an array of events what i want to create calendar events for in the users calendar. I use the createEventWithOptions method and call it on each event in the army in a for loop. The plugin creates multiple calendars one for each event all with the same calendar name if that calendar does not exist in the users calendar app.

**Comment by EddyVerbruggen** [comment]
Do you wait for the `createEventWithOptions` function to return before calling it again?

**Comment by oktapodi** [comment]
Thanks. That solved it by waiting till the success callback is called and then saving the next event.
