### ISSUE TITLE
'deleteEventFromNamedCalendar' Success & Error callback seem to be switched? Success callback doesn't seem to fire. Error callback fires after event is deleted.

### ISSUE THREAD

**Issue by oktapodi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#197]

**Comment by EddyVerbruggen** [comment]
It looks like you're right: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/ios/Calendar.m#L664

That sneaked in with a recent PR. I'll fix it.

**Comment by EddyVerbruggen** [comment]
Should be good now, thanks for reporting it!

**Comment by oktapodi** [comment]
Thanks for the super quick fix!
