### ISSUE TITLE
Android createEventWithOptions with no reminder

### ISSUE THREAD

**Issue by janeksprenger** [EddyVerbruggen/Calendar-PhoneGap-Plugin#201]
Hi

First i want to thank you for your helpful plugin!

I'm using it in a ionic & angular android app.

Everything works fine except of createEventWhithOptions without reminders.

My code:

var calOptions = window.plugins.calendar.getCalendarOptions();
calOptions.firstReminderMinutes = null;
calOptions.secondReminderMinutes = null;

When i create an event with these options, the event reminders are set at the start-time of the event. But i don't want any reminders.

I can set both reminders (first and second) to a number of minutes and it works. But i can't remove one or both of them.

I testet it on a samsung galaxy a5 with android 5.0.2.

Is that a bug or is there something i'm doing wrong?

kind regards

**Comment by aaronprojects** [comment]
Hey,
having the same issue on android (tested it on 4.4). Did you find any solutions/workaround for this?

**Comment by janeksprenger** [comment]
Hi, 
unfortunately not :(

**Comment by EddyVerbruggen** [comment]
Strange, it's something that's added automatically it seems. See [this](http://stackoverflow.com/questions/19019932/create-calendar-event-from-my-app-without-default-reminders) SO issue.

**Comment by EddyVerbruggen** [comment]
I've done a tiny code change in the master branch which will probably not do much (according to the docs it may, but according to the interwebs not so much).

This screenshot was snagged right after I added two events - one without a reminder and one with a reminder:
![screenshot_2015-08-20-16-15-02](https://cloud.githubusercontent.com/assets/1426370/9385414/9c8ff996-4756-11e5-8020-2c82bbb9cc49.png)

This seems correct, but now, after about 5-10 minutes a reminder has been added to the event (the 10 minute default reminder).

Puzzling stuff.

**Comment by EddyVerbruggen** [comment]
OK, solved the puzzle - this is correct behaviour after all:

The event is correctly added without the reminder (see the screenshot above), but once you SYNC that data with Google it will add a default reminder IF you've configured that in your Google account.

This was my default notification setting for new events:
<img width="816" alt="screen shot 2015-08-20 at 16 28 58" src="https://cloud.githubusercontent.com/assets/1426370/9385763/8061920a-4758-11e5-8def-3b07fc28dcee.png">

Which explains the 10 minute reminder it added.

Once I removed that the reminder was no longer added after syncing my Android calendar with the cloud.

I hope this makes sense to you :)

**Comment by janeksprenger** [comment]
Hi Eddy, 
thanks a lot! It works now properly :)
regards
