### ISSUE TITLE
How to find event with ID

### ISSUE THREAD

**Issue by wood1master7** [EddyVerbruggen/Calendar-PhoneGap-Plugin#202]
Hello all!
I was wondering how do you find an event in the calendar, even if its name was changed?

**Comment by ppoisson** [comment]
If iOS use the nice addition Eddy recently made and find it by the id instead.

Thanks!
-Paul


On Jul 29, 2015, at 7:55 PM, wood1master7 <notifications@github.com> wrote:

Hello all!
I was wondering how do you find an event in the calendar, even if its name was changed?

**Comment by wood1master7** [comment]
Thanks, but how do I retrieve the id upon creation?
and how would I do anything like this for android?

**Comment by ppoisson** [comment]
I don’t this it works for Android. This is how I do it…. I am not too sure about Android but this works on iOS.

See: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin <https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin>

/* Straight from the documentation */

var calOptions = cal.getCalendarOptions(); // grab the defaults

calOptions.id = someID; // I save the ID in my database when I create the event,  iOS only, get it from createEventWithOptions (if not found, we try matching against title, etc)

calOptions.calendarName = native_calendar_name; // iOS only

cal.findEventWithOptions(
		title,location,notes,startDate,endDate,calOptions,
		function(msg){ etc…
			

Thanks!
-Paul


On Jul 29, 2015, at 9:25 PM, wood1master7 <notifications@github.com> wrote:

Thanks, but how do I retrieve the id upon creation?
and how would I do anything like this for android?

**Comment by wood1master7** [comment]
Thanks a lot. So no idea on how to pursue Android?
and this works even if they change the title, location, notes, and start/end date?

**Comment by ppoisson** [comment]
I am currently debugging some issues with it still.  In some cases it is working for me and others ist is not.  I think it somehow is getting confused between the find by id and the title, startdate, enddate etc… I am not too sure which is the top “priority” if you will.  I would rather it be by ID if the ID is present.  In my case when I load my app I am checking and comparing the info with the info saved in my DB.  SO I have to call it by ID but I am keeping the title in there.  So if the data does not match up it is supposed to update the calendar data, however, for me in some cases it thinks the ID is not there so it is creating a new entry in the calendar.  So I think I may need a better approach.  Unless Eddy updates the plugin to have a priority level.  Maybe if the title is null and the id is present it uses ONLY the ID?

Eddy?

Thanks!
-Paul


On Jul 30, 2015, at 2:39 PM, wood1master7 <notifications@github.com> wrote:

Thanks a lot. So no idea on how to pursue Android?
and this works even if they change the title, location, notes, and start/end date?

**Comment by wood1master7** [comment]
Sounds good!
Thanks,
James

**Comment by wood1master7** [comment]
I'm trying to keep my app's code universal between Android and IOS through PhoneGap. Is there a way to do both sets of code (for Android and IOS) in the same package of code?

**Comment by EddyVerbruggen** [comment]
Regarding iOS: when passing in the id to search for an event, the `findEventWithOptions` function will try to match [solely against that id](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/ios/Calendar.m#L743-L745). If it's not found it will try to match against the title, etc.

The Android implementation of this plugin currently has no support for finding events by ID. PR's are welcome as I won't be able to do this any time soon.
