### ISSUE TITLE
Calendar don't open on Android and iOS

### ISSUE THREAD

**Issue by Mabudigital** [EddyVerbruggen/Calendar-PhoneGap-Plugin#203]
Hi, I can create events with the plugin but I can't make the calendar open with the "window.plugins.calendar.openCalendar()" function. I'm using Phonegap Build 3.7.0. I search over the internet to find a clue but nothing appears.

Any suggestions?

**Comment by EddyVerbruggen** [comment]
Perhaps you're using an old version?

Try using 4.3.4 from plugins.cordova.io.

**Comment by Mabudigital** [comment]
Thanks for your response!
 In Phonegap Build I'm using <gap:plugin name="nl.x-services.plugins.calendar" /> to grap the last version. Phonegap build give me version 4.2.4. When I try to use <gap:plugin name="nl.x-services.plugins.calendar" version="4.2.8" /> Phonegap Build tell me that is not supported. I'm using Phonegap Build 3.7.0.

**Comment by EddyVerbruggen** [comment]
I'll push this plugin to npm shortly so you can use the latest (4.3.7).

**Comment by EddyVerbruggen** [comment]
It's [on npm](https://www.npmjs.com/package/cordova-plugin-calendar) now.
