### ISSUE TITLE
How do turn-off option "All-day" on the device

### ISSUE THREAD

**Issue by phanthinh** [EddyVerbruggen/Calendar-PhoneGap-Plugin#207]
Hi @EddyVerbruggen 

When using this function "createEventInNamedCalendar" then saw option "All-day" set default to all. Can you help me? 
Code example below: 
$cordovaCalendar.createEventInNamedCalendar({
    title: 'Space Race',
    location: 'The Moon',
    notes: 'Bring sandwiches',
    startDate: new Date(2015, 0, 6, 18, 30, 0, 0, 0),
    endDate: new Date(2015, 1, 6, 12, 0, 0, 0, 0),
    calendarName: 'Cordova Calendar'
  }).then(function (result) {
    // success
  }, function (err) {
    // error
  });

Best regards,
Phan Thinh

**Comment by EddyVerbruggen** [comment]
Wow that code to detect all day events is not ok.. thanks for noticing!
