### ISSUE TITLE
Android app crashes when create event is called.

### ISSUE THREAD

**Issue by Naveenbc** [EddyVerbruggen/Calendar-PhoneGap-Plugin#210]
$cordovaCalendar.createEvent({
	            title: 'Space Race',
	            location: 'The Moon',
	            notes: 'Bring sandwiches',
	            startDate: new Date(2015, 7, 15, 18, 30, 0, 0, 0),
	            endDate: new Date(2015, 7, 15, 19, 0, 0, 0, 0)
	        }).then(function (result) {
	        	alert("Event created successfully");
	        }, function (err) {
	            alert("There was an error: " + err);
	        });

when the above function is called app crashes with below error, saying unfortunately app stopped working
![crash](https://cloud.githubusercontent.com/assets/13797701/9274624/00af731c-42b5-11e5-979b-22f71476d25f.PNG)

**Comment by EddyVerbruggen** [comment]
Looks like creation of the reminder fails. I will catch this error and make sure your app doesn't crash.

**Comment by EddyVerbruggen** [comment]
Added a catch and log. Also, when creating a reminder fails the event has been created successfully so the success callback will be invoked (and the error logged).

Available in 4.3.7.

**Comment by Naveenbc** [comment]
Thanks a lot EddyVerbruggen
