### ISSUE TITLE
ios 7 and 8 crash when adding event with options or interactively

### ISSUE THREAD

**Issue by robertesler** [EddyVerbruggen/Calendar-PhoneGap-Plugin#212]
I saw last year's reference to this issue (e.g., issue #56 IOS 6.1 crashes).  Thought it was my startDate and endDate as well but it doesn't seem to help.   This plugin crashes anytime I try to save an event interactively or with options on iOS 7 or iOS 8 w/ 32-bit devices.  It throws an exception (see below) and references line 545 in Calendar.m.
  It works fine however on Android 4.4 and higher.  

2015-08-19 10:26:44.553 AppName[1618:60b] -[__NSDictionaryI length]: unrecognized selector sent to instance 0x16d468b0
2015-08-19 10:26:44.558 AppName[1618:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI length]: unrecognized selector sent to instance 0x16d468b0'
*** First throw call stack:
(0x2d6faf83 0x37eabccf 0x2d6fe917 0x2d6fd203 0x2d64c768 0x2de67e11 0x2de6cbb1 0x2de67b6f 0x2e03ff23 0x2de7333f 0x2de72e29 0x2de71233 0x2de71123 0x2df9a3cd 0x2df32079 0x2df2e705 0x2ff4d037 0x300b3c45 0x2ff4d037 0x2ff4cfd7 0x2ff4cfb1 0x2ff38717 0x2ff4ca2f 0x2ff4c701 0x2ff476cb 0x2ff1c8cd 0x2ff1af77 0x2d6c620b 0x2d6c56db 0x2d6c3ecf 0x2d62eebf 0x2d62eca3 0x32534663 0x2ff7b14d 0xffc03 0x383b8ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jjdelgado** [comment]
Really strange. For me it's the opposite. 
It works perfectly on iOS 8 but keeps crashing on Android (5.1). 
And it's always when I return to app, after confirm the event in calendar.

**Comment by robertesler** [comment]
Yes, that is strange.  Same behavior too.  When using createEventInteractively() it loads the calendar fine, but when I choose "Done" it crashes with the previous exception.  By any chance are you using ngCordova?  I'm using it with the Ionic Framework.  Not sure if this has anything to do with it.

**Comment by jjdelgado** [comment]
Yes. I'm using ngCordova with ionic framework.

**Comment by EddyVerbruggen** [comment]
I've added a bit of logging which hopefully shed some light on the case. Also tweaks some internal cordova plugin flow things which may help, but I can't promise anything because I can't reproduce this error on any platform.

4.3.7 contains these tweaks. Feel free to reopen (with preferably more info, logfiles etc) if it still crashes.

**Comment by robertesler** [comment]
Thanks Eddy.  I appreciate the time in updating the logging and in the plugin itself.  It appears so far it was two things.  The main issue with the crash was that my "notes:" field in the createEventInteractively argument was either too long or contained html.  I don't know which, but for now I won't use it anyway.  The other problem I had was referencing data from within my angular.controller().  This didn't cause a crash, however, it would not call the calendar view if I referenced data from an array created from within my controller.  However, it worked if I passed the data from my view via an ng-directive.   
The following code worked:
```
var test = angular.module('testCal', []);
test.controller('eventCtrl', function($scope, $cordovaCalendar, $ionicPlatform) {

//called from my view using ng-click="createCalendarEvent(title, location, date, end)"

$scope.createCalendarEvent = function(eventTitle, eventLocation, eventDate, endDate) {
	$ionicPlatform.ready(function () {	 
        $cordovaCalendar.createEventInteractively({
		title: eventTitle,
                location: eventLocation,
                notes: "Generated by the App",
                startDate: eventDate,
                endDate: endDate  
		}).then(function (result) {
            console.log("Event created successfully" + result);
     });
        }, function (err) {
            console.error("There was an error: " + err);
        }); //end read
    
	 };//end createCalendarEvent
});
```
The following didn't work in iOS, even though the data from the arrays are good. (note: uses xml2json.js) It does work on Android 5.0 or higher.
```
var test = angular.module('testCal', []);

test.controller('eventCtrl', function($scope, $cordovaCalendar, $ionicPlatform, rssFeed) {

$scope.loadRss = function() {
		rssFeed.get('http://www.anywebblog.com/feed')
				.success(function(data){
					
					$scope.rssTitle = [];
					$scope.rssTitle = rssFeed.getTitle(data);
					$scope.rssDescription = [];
					$scope.rssDescription = rssFeed.getDescription(data);
					$scope.rssDate = [];
					$scope.rssDate = rssFeed.getDate(data);
					$scope.rssLocation = [];
					$scope.rssLocation = rssFeed.getLocation(data);
   			});
	};

 $scope.$on('$ionicView.enter', function() {
      $scope.loadRss();
    }); 

$scope.createCalendarEvent = function(index) {
	$ionicPlatform.ready(function () {	 
        $cordovaCalendar.createEventInteractively({
		title: $scope.rssTitle[index],
                location: $scope.rssLocation[index],
                notes: "Generated by the App", //this crashed when from my rss feed
                startDate: $scope.rssDate[index],
                endDate: $scope.rssDate[index] 
		}).then(function (result) {
            console.log("Event created successfully" + result);
     });
        }, function (err) {
            console.error("There was an error: " + err);
        }); //end read
    
	 };
});

test.factory('rssFeed', function($http, $sce) {
	
	return {
		get : function(feedUrl) {
        	return $http({
				url:  feedUrl,
				method: 'GET'
			})
			
		}, // end get
		
		getDescription: function(data) {
		
				var feed = [];
		 		var items = x2js.xml_str2json(data);

					for(var i = 0; i < items.rss.channel.item.length; i++) {
						feed.push($sce.trustAsHtml(items.rss.channel.item[i].description));
		 			}
			return feed;
		},// end parse
		
		getDescriptionNews: function(data) {
		
				var feed = [];
		 		var items = x2js.xml_str2json(data);
//				console.log(items.rss.channel.item.length);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						feed.push($sce.trustAsHtml(items.rss.channel.item[i].description.toString()));
		 			}
			return feed;
		},// end parse
		
		getTitle: function(data) {
		
				var feed = [];
		 		var items = x2js.xml_str2json(data);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						feed.push(items.rss.channel.item[i].title);
		 			}
			return feed;
		},
		
		getDate: function(data) {
				var feed = [];
		 		var items = x2js.xml_str2json(data);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						var d = new Date(items.rss.channel.item[i].pubDate);
						feed.push(d);
		 			}
			return feed;
		},
		
		getLocation: function(data) {
				var feed = [];
				var location = [];
		 		var items = x2js.xml_str2json(data);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						feed.push(items.rss.channel.item[i].description);
						var index = feed[i].indexOf('<br/>');
						var slicedString = feed[i].slice(0, index);
						location.push(slicedString);
		 			}
			
				return location;					
		},
		
		getContent: function(data) {
				var feed = [];
		 		var items = x2js.xml_str2json(data);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						feed.push( $sce.trustAsHtml(items.rss.channel.item[i].encoded.toString()) );
		 			}
			return feed;
		},
		
		getThumbnail: function(data) {
				var feed = [];
		 		var items = x2js.xml_str2json(data);
					for(var i = 0; i < items.rss.channel.item.length; i++) {
						if(items.rss.channel.item[i].thumbnail)
							feed.push( items.rss.channel.item[i].thumbnail._url );
						else
							feed.push("img/ionic.png");
							
		 			}
			return feed;
		}
	}//end return
	
});
```

**Comment by EddyVerbruggen** [comment]
Thanks for sharing this!

**Comment by jonmaim** [comment]
In my case, providing `null` as `endTime` for function `createEventInteractivelyWithOptions` is causing an app crash (iOS).

**Comment by bau720123** [comment]
same situation that I post here
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/213

**Comment by EddyVerbruggen** [comment]
@jonmaim You're right, passing a `null` `endDate` will crash. I've fixed that now but beware that if you don't pass an `endDate` iOS will set a default for you (`startDate` + 1 hour). That's not the plugin doing that, it's iOS itself.

**Comment by jonmaim** [comment]
@EddyVerbruggen thanks!

**Comment by bau720123** [comment]
hi everybody
for now I use 4.4.0 version but still face iOS 8.4.1 (12H321) crash (but Android 4.4.2 is totally no problem at all) problem
Everyone's situation ?
