### ISSUE TITLE
["createEvent" and "createEventWithOptions"]'s title、location、notes value will all null with Android 4.4.2

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Calendar-PhoneGap-Plugin#216]
hi @EddyVerbruggen 
I am using PGB 5.2.0 with your latest version from npm
https://www.npmjs.com/package/cordova-plugin-calendar

this is my full example
```
var title = "title";
var newTitle = "newtitle";
var location = "location"
var notes = "notes";
var startDate = new Date(new Date().getTime());
var endDate = new Date(new Date().getTime() + 3*24*60*60*1000);
var futureDate = new Date(new Date().getTime() + 6*24*60*60*1000);
var calendarName = "mycalendar";
window.plugins.calendar.createEvent(title, location, notes, startDate, endDate, success, error);
```

when in Android 4.4.2，the "title"、"location"、"notes" attribute value will null (but iOS 8.4.1 work perfect)
this is my screenshot
ASUS Zenphone Android 4.4.2
![screenshot_2015-08-24-16-08-52](https://cloud.githubusercontent.com/assets/5110085/9435509/3073858e-4a7b-11e5-9bbb-5e93823f692d.jpg)

PS
other method like "createEventWithOptions" have the totally same issues

**Comment by kodl** [comment]
:+1:

**Comment by bau720123** [comment]
hi @kodl 
did you have same problem ?

**Comment by kodl** [comment]
@bau720123 yes ... I set title and location (and the rest drom evample), call createEventInteract ... but in dialog has title and location empty (notes, start, end .. and rest are OK).
Tested on Galaxy S3 neo GT-I93011 , Android 4.4.2, core 3.4.0-5034464

**Comment by EddyVerbruggen** [comment]
Made an error, thanks for the quick test and feedback guys. I'll be kicking out a new version asap.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen reply

**Comment by bau720123** [comment]
just feedback
problem solved in 4.4.0 version

**Comment by EddyVerbruggen** [comment]
:+1: 
Thanks for the test!

**Comment by kodl** [comment]
confirm :+1:  ... fixed ..
Thank you for realy fast fix ;)
