### ISSUE TITLE
"listEventsInRange" seem always trigger the success callback but output a null json value

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Calendar-PhoneGap-Plugin#219]
Android 4.4.2
this is my full example
I am very sure that I have a event created start at startDate and end at endDate
```
var startDate = new Date(new Date().getTime());
var endDate = new Date(new Date().getTime() + 3*24*60*60*1000);
var futureDate = new Date(new Date().getTime() + 6*24*60*60*1000);
window.plugins.calendar.listEventsInRange(startDate, futureDate, success, error);
```
no mater the "startDate" and "futureDate" is
it seem always trigger the success callback but output a null json value => []

**Comment by EddyVerbruggen** [comment]
Just tried this and couldn't find a problem. Note that events must be fully inside the date range, so events starting after the startdate and finishing after the enddate will not be included.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen detail reply
problem solved
thanks
