### ISSUE TITLE
The ID attribute of the plugin tag in plugin.xml still references the pre-npm value

### ISSUE THREAD

**Issue by alexbuijs** [EddyVerbruggen/Calendar-PhoneGap-Plugin#222]
The id attribute in the main tag inside plugin.xml is still nl.x-services.plugins.calendar instead of cordova-plugin-calendar.

This causes the plugin to be installed in the wrong directory and the prepare command trying to reinstall the plugin every time, only to find out is was already installed:

````
$ cordova prepare
Discovered plugin "cordova-plugin-calendar" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-calendar@4.3.9" via npm
Plugin "nl.x-services.plugins.calendar" already installed on android.
Plugin "nl.x-services.plugins.calendar" already installed on ios.

**Comment by EddyVerbruggen** [comment]
That's not cool. I was hoping changing the ID would not be necessary.

**Comment by EddyVerbruggen** [comment]
Should be fine now - I mistakenly changed the cordova.id in package.json to the wrong value.
4.4.0 is on npm.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I am using PGB 5.2.0 with 4.4.0 version from npm
I download the apk or ipa and uncompress it
that I found in the cordova_plugin.js still maintain the "nl.x-services.plugins.calendar" but not "cordova-plugin-calendar"
although it still work
```
{
        "file": "plugins/nl.x-services.plugins.calendar/www/Calendar.js",
        "id": "nl.x-services.plugins.calendar.Calendar",
        "clobbers": [
            "Calendar"
        ]
    },
    {
        "file": "plugins/nl.x-services.plugins.calendar/test/tests.js",
        "id": "nl.x-services.plugins.calendar.tests"
    },
```

so...just want to ask，is that behavior normal ?

**Comment by alexbuijs** [comment]
Hi Eddy, thanks for responding so quickly! Actually, I think changing the ID in package.json does not solve the issue:

````
$ cordova prepare
Discovered plugin "cordova-plugin-calendar" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-calendar@4.4.0" via npm
Installing "nl.x-services.plugins.calendar" for android
Installing "nl.x-services.plugins.calendar" for ios
````
And when run again:
````
cordova prepare
Discovered plugin "cordova-plugin-calendar" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-calendar@4.4.0" via npm
Plugin "nl.x-services.plugins.calendar" already installed on android.
Plugin "nl.x-services.plugins.calendar" already installed on ios.
````
When I change the config.xml to point to it's old value:
````
<plugin name="nl.x-services.plugins.calendar" spec="4.4.0" />
````
, it can't find it on npm:
````
cordova prepare
Discovered plugin "nl.x-services.plugins.calendar" in config.xml. Installing to the project
Fetching plugin "nl.x-services.plugins.calendar@4.4.0" via npm
Fetching plugin "nl.x-services.plugins.calendar@4.4.0" via cordova plugins registry
````
Isn't it possible to change the ID in plugin.xml (and package.json) to the npm name?

**Comment by EddyVerbruggen** [comment]
@alexbuijs It is possible but I rather not. Long story, I'm trying to not break every system this plugin is used on.

I don't have that same behavior you're seeing - running prepare again doesn't refetch the plugin. Could it be you're using an older version of the cordova cli?

My steps:

```
cordova create caltest
cd caltest
cordova platform add ios
cordova platform add android
cordova plugin add cordova-plugin-calendar
```

Now `cordova prepare` never refetches the plugin. My cordova cli version is 5.1.1 (`cordova --v`).

**Comment by alexbuijs** [comment]
Right, the confusion arises from the saved name in config.xml.

When I run:
```
cordova plugin add cordova-plugin-calendar --save
````
This gets saved to config.xml:
````
<plugin name="nl.x-services.plugins.calendar" spec="~4.4.0" />
````
Now when I follow these steps:
```
cordova plugin rm nl.x-services.plugins.calendar
cordova prepare
````
, it can't find nl.x-services.plugins.calendar@4.4.0 on either npm or cordova plugins registry.

Also notice how I need to call cordova plugin rm with the nl.x-services.plugins.calendar name. Otherwise cordova (5.2.0) will not recognize it.

It is also possible to specify this in config.xml:
````
<plugin name="cordova-plugin-calendar" spec="~4.4.0" />
````
But then the aforementioned behaviour occurs (cordova prepare trying to reinstall the plugin over and over again).

So the problem is: cordova cli uses the npm name to find plugins, but it uses the ID from plugin.xml to save the plugin in the plugin directory and reference it in later commands.

When these names differ, it makes it hard to use config.xml as a reference for installed plugins and their specific versions and for bootstrapping the app.

**Comment by EddyVerbruggen** [comment]
Got it, that's not ok. Thanks for elaborating. I have to think about this a bit.

**Comment by EddyVerbruggen** [comment]
Hey @alexbuijs, 4.4.1 is now on npm and dropped the old plugin id. I hope this doesn't hurt anyone.

**Comment by alexbuijs** [comment]
Great, thanks! :+1:
