### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by satchmo7** [EddyVerbruggen/Calendar-PhoneGap-Plugin#229]
App no longer builds via the command line after the plugin is installed?

**Comment by signalwerk** [comment]
same problem here. here a short snippet:

```
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:306:55: error: expected '>'
                       calendars: (NSArray<EKCalendar *>*)  calendars {
                                                      ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:306:56: error: expected ')'
                       calendars: (NSArray<EKCalendar *>*)  calendars {
                                                       ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:306:35: note: to match this '('
                       calendars: (NSArray<EKCalendar *>*)  calendars {
                                  ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:135:26: error: expected '>'
      NSArray<EKCalendar *>* calendars = nil;
                         ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:135:27: error: expected identifier or '('
      NSArray<EKCalendar *>* calendars = nil;
                          ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:138:11: error: use of undeclared identifier 'calendars'
          calendars = self.eventStore.calendars;
          ^
/{{path}}/Plugins/cordova-plugin-calendar/Calendar.m:138:39: warning: 'calendars' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
          calendars = self.eventStore.calendars;
```

**Comment by EddyVerbruggen** [comment]
That's from a PR I integrated yesterday. I'll check it in a few hours - if you can't wait, use the 4.4.1 version.

**Comment by satchmo7** [comment]
Hi, can you please post a link to the 4.4.1 version

**Comment by signalwerk** [comment]
@satchmo7 
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/tree/4.4.1

or for cordova 
```
cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git#4.4.1
```

I also took the version I had before (4.3.0) and it worked again.

**Comment by satchmo7** [comment]
Perfect, thank you

**Comment by satchmo7** [comment]
Can anyone put up a simple demo of adding an event to the devices calendar?

**Comment by satchmo7** [comment]
I have this in the head of my page:

<script type="text/javascript">
		 function calendar_events(){
			 var startDate = new Date(2015,8,25,18,30,0,0,0); // beware: month 0 = january, 11 = december
			  var endDate = new Date(2015,8,25,19,30,0,0,0);
			  var title = "Skype meeting With Lead";
			 //var location = "myleads.html";
			  var notes = "Need to do a skype meeting with the lead.";
			  var success = function(message) { alert("Success: " + JSON.stringify(message)); };
			  var error = function(message) { alert("Error: " + message); };
			  // window.plugins.calendar.listEventsInRange(startDate,endDate,success,error);
			
			//  window.plugins.calendar.createCalendar(calendarName,success,error);
			  window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,success,error);
			  alert("here");
		 }
	</script>

And then call it with <button onclick="calendar_events()">create calendar</button> but nothing happens, my understanding is this would add the event to my native calendar, am i wrong?

**Comment by EddyVerbruggen** [comment]
@satchmo7 @signalwerk Thanks for notifying me, the master branch should now we usable again with systems not yet building with XCode 7.

@satchmo7 your code should work, but can you please first add an `alert(1)` at the start of the `calendar_events` function? I'm suspecting CSP is in play.

If that alert doesn't fire, remove any csp metatag.

If it does show the alert you may have a JS error somewhere. Add a JS catch all handler to catch it:
```js
window.error = function(a,b,c) {
  alert(a);
}
```

**Comment by satchmo7** [comment]
Hi Eddy,

I have the plugin working locally, I ideally need it to work from a remote
server, as the page that uses it is pulled in via an in App Browser, can it
still work if the plugin is hosted on a remote server in the same directory
as the page that will use it?

Kind regards,
Ash


On 07/09/2015 18:30, "Eddy Verbruggen" <notifications@github.com> wrote:

> @satchmo7 <https://github.com/satchmo7>  @signalwerk
> <https://github.com/signalwerk>  Thanks for notifying me, the master branch
> should now we usable again with systems not yet building with XCode 7.
> 
> @satchmo7 <https://github.com/satchmo7>  your code should work, but can you
> please first add an alert(1) at the start of the calendar_events function? I'm
> suspecting CSP is in play.
> 
> If that alert doesn't fire, remove any csp metatag.
> 
> If it does show the alert you may have a JS error somewhere. Add a JS catch
> all handler to catch it:
> 
> window.error = function(a,b,c) {
>   alert(a);
> }
> 
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/229#issueco
> mment-138346162> .
> 
>   
> 

Ashley Norton
Digital Development Manager

Direct Dial: 01223 492243
Switchboard: 01223 499450




CAUTION - This message may contain privileged and confidential information
intended only for the use of the addressee named above. If you are not the
intended recipient of this message you are hereby notified that any use,
dissemination, distribution or reproduction of this message is prohibited.
Any views expressed in this message are those of the individual sender and
may not necessarily reflect the views of Bright Publishing Ltd.

Please consider the environment before printing this email

**Comment by EddyVerbruggen** [comment]
That should be possible, as long as you add `<script src="cordova.js"/>` in the remote html file. If `deviceready` fires you're good.

**Comment by satchmo7** [comment]
Cordova.js is added and hosted next to the .html file and deviceready is fired when the page is loaded via the in App Browser, but it still doesn't work, have you got any other ideas?

**Comment by signalwerk** [comment]
@satchmo7 I don't wanna be rude but you should go to stackoverflow (or that alike) if you have general problems with phonegap. this is a bug report. If you have a new bug to report please open a new issue. This bug is about the problem with the build. I'm subscribed to this bug because I'm interested about the work @EddyVerbruggen did for us and how the progress on this bug is. 
@EddyVerbruggen thank you for your update. Didn't tested it yet but the commit looks good though.
