### ISSUE TITLE
Error on iOS when deleting event

### ISSUE THREAD

**Issue by RobertDoc** [EddyVerbruggen/Calendar-PhoneGap-Plugin#231]
I've imported the demo project and this shows when I try to delete an event from the calendar:

[Calendar findEKEventsWithTitle:location:notes:startDate:endDate:calendar:]: unrecognized selector sent to instance 0x789320f0'

*** First throw call stack:

CoreFoundation                      0x001f11e4 __exceptionPreprocess + 180
libobjc.A.dylib                     0x021468e5 objc_exception_throw + 44
CoreFoundation                      0x0028e243 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
CoreFoundation                      0x001e150b ___forwarding___ + 1019
CoreFoundation                      0x001e10ee _CF_forwarding_prep_0 + 14
HelloCordova                        0x000bb65f __45-[Calendar deleteEventFromCalendar:calendar:]_block_invoke + 383
libdispatch.dylib                   0x027047b8 _dispatch_call_block_and_release + 15
libdispatch.dylib                   0x027194d0 _dispatch_client_callout + 14
libdispatch.dylib                   0x02707eb7 _dispatch_root_queue_drain + 291
libdispatch.dylib                   0x02708127 _dispatch_worker_thread2 + 39
libsystem_pthread.dylib             0x02a4430f _pthread_wqthread + 845
libsystem_pthread.dylib             0x02a41eea start_wqthread + 30
)

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by syndbg** [comment]
device?

**Comment by RobertDoc** [comment]
iOS sim and iPhone 4-5 and 6.

**Comment by ndacosta** [comment]
I have The same problem.....

**Comment by RobertDoc** [comment]
I've given up by now :+1:

**Comment by EddyVerbruggen** [comment]
I'm afraid this sneaked in with PR #228, fixed now. Seems like a good moment to create a release.
