### ISSUE TITLE
Cannot read property 'calendar' of undefined

### ISSUE THREAD

**Issue by Zapmobilegames** [EddyVerbruggen/Calendar-PhoneGap-Plugin#232]
Hello Eddy,
I downloaded the demo project and installed it using Intel XDK. I've built the solution and installed the apk on my Android tablet. After the launch, if I press on whatever button I always got this kind of issue (i.e.):

Uncaught TypeError: Cannot read property 'calendar' of undefined; file:///android_asset/www/js/demo.js: 52

Any suggestion?

**Comment by Zapmobilegames** [comment]
Oh my god! Sorry for the silly question, I solved now. After the project download and import, I have to manually reference to the third-party plugin in the Projects tab:
Projects -> Add a Third-Party Plugin -> Get Plugin form the Web 
and following this instructions (https://software.intel.com/en-us/xdk/docs/adding-third-party-plugins-to-your-xdk-cordova-app) I finally got it.

**Comment by EddyVerbruggen** [comment]
:+1: :+1:
