### ISSUE TITLE
Does createEventInteractively should work on iOS ?

### ISSUE THREAD

**Issue by elbidone** [EddyVerbruggen/Calendar-PhoneGap-Plugin#237]
Hi, 

I used cli-5.2.0 (means iOS 3.9.1) and last version of plugin (4.4.3)

When I use createEventInteractively on iOS device it crashes the App. The table of basic operation compatibility shown on README seems to indicate that it should work. I've used the code suggested as example on github.

```js
var startDate = new Date(2015,2,15,18,30,0,0,0); // beware: month 0 = january, 11 = december
var endDate = new Date(2015,2,15,19,30,0,0,0);
var title = "My nice event";
var address = "Home";
var description = "Some notes about this event.";
var success = function(message) { alert("Success: " + JSON.stringify(message)); };
var error = function(message) { alert("Error: " + JSON.stringify(message)); };
window.plugins.calendar.createEventInteractively(title,address,description,startDate,endDate,success, error);
```
If I use createEvent instead of createEventInteractively it works, adding event silently.

**Comment by EddyVerbruggen** [comment]
Hmm, weird just tried this exact code on the iPhone 6S Simulator (iOS 9.something): works.

When does it crash, what's the message, and which device/iOS?

**Comment by elbidone** [comment]
I've tested on device, iOS 9.0.2.
It crashes (close the App) when I call the plugin, without any message.

**Comment by elbidone** [comment]
Same code works fine on Android.

**Comment by scurker** [comment]
I have a pull request (#233) related to the iOS crashing. Issue #213 is related to this as well. 

You can read my [full comment](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/213#issuecomment-142355905) there for details, but in short the default options aren't set consistently. If you look at the source, it's using [`interval`](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/ios/Calendar.m#L580) when the default options is setting [`recurrenceInterval`](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/www/Calendar.js#L52)

@elbidone You can monkey patch this by using `createEventInteractivelyWIthOptions()` and setting `interval` on the options object instead.

@EddyVerbruggen If you need more details, I can provide the xcode crash details, but I've been able to replicate this across every iOS device.

**Comment by EddyVerbruggen** [comment]
Thanks guys, I will look at it later today.. been a bit busy the past week.

**Comment by EddyVerbruggen** [comment]
@scurker thanks for the fix, it should have been `recurrenceInterval` as you figured out.

Available in 4.4.4.

Thanks!

**Comment by elbidone** [comment]
It continues to crash. I've tested with version 4.4.4 of plugin, calling createEventInteractivelyWithOptions and createEventInteractively

See below the calls
```js
var calOptions = window.plugins.calendar.getCalendarOptions();
calOptions.interval = 1;
window.plugins.calendar.createEventInteractivelyWithOptions(title,address,description,startDate,endDate,calOptions, success,error);
```

```js
window.plugins.calendar.createEventInteractively(title,address,description,startDate,endDate,success,error);
```

Did I miss stg ?

**Comment by jomarocas** [comment]
im in the same and i see this issue is some old

my code 

```
  var titlecustom = title;
  var loccustom = 'Aquí';
  var notescustom = description;
  var gethourbegincustom = hour1;
  var gethourendcustom = hour2;
  var startdatecustomize = date1;
  var endDatecustomize = date2;
  var datebeginevent = moment().format(startdatecustomize + ' ' + gethourbegincustom);
  var dateendevent = moment().format(endDatecustomize + ' ' + gethourendcustom);
  var startDatecustom = new Date(datebeginevent);
  var endDatecustom = new Date(dateendevent);
window.plugins.calendar.createEventInteractively(titlecustom, loccustom, notescustom, startDatecustom, endDatecustom, onSuccess, onError)
window.plugins.calendar.createEvent(titlecustom, loccustom, notescustom, startDatecustom, endDatecustom, onSuccess, onError)
```

i use moment for detect local time for each user create event
i use createEvent and createEventInteractively, but without success

```
[3062:104178] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x108c5ed80'
*** First throw call stack:
(
    0   CoreFoundation                      0x0000000108a36d85 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010c43ddeb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000108a3fd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x0000000108985cfa ___forwarding___ + 970
    4   CoreFoundation                      0x00000001089858a8 _CF_forwarding_prep_0 + 120
    5   OncologiÃÅa Clinica del country     0x00000001087846c1 __35-[Calendar createEventWithOptions:]_block_invoke + 337
    6   libdispatch.dylib                   0x000000010cd04d9d _dispatch_call_block_and_release + 12
    7   libdispatch.dylib                   0x000000010cd253eb _dispatch_client_callout + 8
    8   libdispatch.dylib                   0x000000010cd0db2f _dispatch_root_queue_drain + 1829
    9   libdispatch.dylib                   0x000000010cd0d405 _dispatch_worker_thread3 + 111
    10  libsystem_pthread.dylib             0x000000010d0624de _pthread_wqthread + 1129
    11  libsystem_pthread.dylib             0x000000010d060341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

```
this is the log http://pastebin.com/iv97fmdt
 if any have the solution please post here
