### ISSUE TITLE
"null" always gets added to event description

### ISSUE THREAD

**Issue by aaronprojects** [EddyVerbruggen/Calendar-PhoneGap-Plugin#245]
Hey,

I'm creating events like this:

```javascript
window.plugins.calendar.createEventWithOptions(eventToCreate.title, eventToCreate.location, eventToCreate.shortdescription, eventToCreate.start, eventToCreate.end, calendarOptions, onSuccess, onError);
```

This will result in a event on android (5.1) like this:
![Created event](http://www.neodym-ide.org/wp-content/uploads/2015/10/Screenshot_2015-10-22-13-44-20.png)

As you can see in the description there is a "null" at the end. This happens for each single event.

Any idea what's going wrong here?

Regards :)

**Comment by othmaan** [comment]
Same here

**Comment by EddyVerbruggen** [comment]
Funny case - can you try updating from the master repo and see if it is now fixed?

**Comment by aaronprojects** [comment]
Works now, thanks a lot :)
