### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by TobiasFriberg** [EddyVerbruggen/Calendar-PhoneGap-Plugin#251]
I have an issue with missing functions, ex: openCalendar(). I am user v 4.4.4.

These are the functions available only.
createCalendar: function(options)
createEvent: function(options)
createEventInNamedCalendar: function(options)
createEventInteractively: function(options)
createEventWithOptions: function(options)
deleteCalendar: function(calendarName)
deleteEvent: function(options)
findAllEventsInNamedCalendar: function(calendarName)
findEvent: function(options)
listCalendars: function()
listEventsInRange: function(startDate, endDate)
modifyEvent: function(options)

As you can see, there are a some missing functions.

**Comment by mnewmedia** [comment]
Not really a usefull issue, because there is already a list of which functions are implemented in which versions [here](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin#3-usage). But i'm shure Eddy would love to get a Pull Request of you =)

**Comment by TobiasFriberg** [comment]
@mnewmedia , I'm not sure we unsertand eachother. The functions implemented are missing for me. I want to call the function openCalendar(), but for me, it does not exist. (as you can see above in the list). It clearly says it should be implemented, but it's some kind of bug for me. I cannot use it.

**Comment by mnewmedia** [comment]
Then maybe show some code?
What you get with console.log(window.plugins)

Von meinem iPhone gesendet

**Comment by TobiasFriberg** [comment]
I only get the Keyboard tho, but when i log the $cordovaCalendar from the controller i get the list above. And no openCalendar..

**Comment by mnewmedia** [comment]
Then you use ng-cordova.. I don't use it, but i think they wrap all functions from this plugin to create a service `$cordovaCalendar`. Maybe they are not up to date or did forget to wrap this function. Then you have to open an issue there.. 
Or use this plugin without the ng-cordova stuff.. 

now you can close this issue, i think ;)

**Comment by TobiasFriberg** [comment]
I use ng-cordova, but i guess they missed something then.. I've updated everything so it all should be up to date. Thanks anyway.

**Comment by EddyVerbruggen** [comment]
Please feel free to fork ngCordova and extend support [of this file](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/calendar.js). It's entirely opensource and community driven, so your help is much appreciated if you think stuff is missing.
