### ISSUE TITLE
Android Build Failed after adding the Plugin

### ISSUE THREAD

**Issue by codecrab-studios** [EddyVerbruggen/Calendar-PhoneGap-Plugin#258]
Hey Eddy

Hope you are well.. I really like this Plugin, and how it worked smooth. it works fine on iOS but when i try to create a Build it gave me an error. The Error is display below
![screen shot 2015-12-10 at 7 12 08 pm](https://cloud.githubusercontent.com/assets/16228380/11716800/5750b7ca-9f72-11e5-84bb-a61f25542e82.png)

Check the above screenshot so you know about it more.

Another Screenshot when i try to run it in Android Emulator

![screen shot 2015-12-10 at 7 20 12 pm](https://cloud.githubusercontent.com/assets/16228380/11716914/10136dde-9f73-11e5-87d0-29807e18f7df.png)

Same thing happens here too... Please help!!

**Comment by EddyVerbruggen** [comment]
Looks like your build can't resolve [this support library](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/plugin.xml#L66). Can you run `android` from a Terminal and see that the support lib is up to date? It's somewhere near the bottom of the SDK manager window.

**Comment by codecrab-studios** [comment]
ok it showed me Updates Available... Those are downloading now.. Lets see. how it goes!

**Comment by codecrab-studios** [comment]
![screen shot 2015-12-10 at 7 30 09 pm](https://cloud.githubusercontent.com/assets/16228380/11717132/72e7a06e-9f74-11e5-9b7b-2d7406542250.png)

**Comment by EddyVerbruggen** [comment]
If that works I think I need to set a minimum required version of the support lib in plugin.xml.. not sure which version yet though.

**Comment by codecrab-studios** [comment]
Guess what, It worked :)

**Comment by EddyVerbruggen** [comment]
:beers: 

I'll look into that minversion thingy.

**Comment by codecrab-studios** [comment]
sure!

**Comment by codecrab-studios** [comment]
It built the Apk, now trying to  do "ionic emulate android", its stuck at:  


Total time: 10.944 secs
Built the following apk(s):
    /Users/apple/Desktop/Ionic-MobileProjects/ChurchApp/platforms/android/build/outputs/apk/android-debug.apk
Installing app on emulator...
Using apk: /Users/apple/Desktop/Ionic-MobileProjects/ChurchApp/platforms/android/build/outputs/apk/android-debug.apk

not doing anything after that!

**Comment by EddyVerbruggen** [comment]
Can you send me the apk perhaps (eddyverbruggen at gmail)

**Comment by codecrab-studios** [comment]
it worked just now, took so much time!
