### ISSUE TITLE
Build fails using cordova-ios@4

### ISSUE THREAD

**Issue by pwasem** [EddyVerbruggen/Calendar-PhoneGap-Plugin#259]
As of now cordova-plugin-calendar seems to have a compatibility issue with latest cordova-ios:

cordova build ios fails using: 
* cordova-ios@4.0.0
* cordova-plugin-wkwebview-engine@1.0.0
* cordova-plugin-calendar@4.4.6

But I am sure this will be fixed soon, isn't it?

Thank you in advance!

**Comment by EddyVerbruggen** [comment]
If anyone can take a look I'd be very happy. There's a lot of work to be done with cordova-ios-4 being released so I can't say when exactly I will get to it.

**Comment by ritterb82** [comment]
Any update on this item?

**Comment by EddyVerbruggen** [comment]
It was easier than I anticipated at first, so yep it's available with 4.4.6.
