### ISSUE TITLE
[iOS] hasReadWritePermission always returns true

### ISSUE THREAD

**Issue by 1b0t** [EddyVerbruggen/Calendar-PhoneGap-Plugin#260]
On iOS the hasReadWritePermission method always returns true even when calendar access was denied in iOS settings.

**Comment by EddyVerbruggen** [comment]
Yeah it's only implemented for Android atm. For Android 6's new permission model. Would be nice to have it for iOS as well.

**Comment by 1b0t** [comment]
implemented. https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/pull/261

**Comment by EddyVerbruggen** [comment]
Awesomeness!
