### ISSUE TITLE
Plugin broke my calendar app

### ISSUE THREAD

**Issue by derksacklowski** [EddyVerbruggen/Calendar-PhoneGap-Plugin#264]
Hi,

after testing the app my calendar app is broken (android 6.0). I deleted app and system cache, with no luck so far. i guess i messed up adding an event and somehow the native calendar app broke.

i attached a crash log
[LogCat.txt](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/files/88557/LogCat.txt)

**Comment by jomarocas** [comment]
i have the same issue, when i click in open calendar the app of calendar crash, but create event list calendar, i use native calendar of google and moto x 2

**Comment by jomarocas** [comment]
install digical for use calendar, the native calendar i dont know why no wroking

**Comment by thedewi** [comment]
I have found Android's local calendar storage to be quite fragile. A quick way to reset it is to visit `Settings > Apps > Calendar Storage` and click `Clear data`. Then view the Calendar app and wait for it to refresh from the cloud.

**Comment by derksacklowski** [comment]
it started working again a few months after my initial post. Thanks for your response :)
