### ISSUE TITLE
Issue related to the new Cordova version CLI >5

### ISSUE THREAD

**Issue by Zapmobilegames** [EddyVerbruggen/Calendar-PhoneGap-Plugin#265]
Hello,
it seems the plugin is broken, I can't add anymore in my Intel XDK app. Is this maybe?

"You'll have to ask the authors to update them. Tell them to read: http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html (the 1st link in that post points to an API change doc that gives them instructions on how to update)"

**Comment by Zapmobilegames** [comment]
Gotcha! Could you please fix it?

:compileArmv7ReleaseJava.../MyApp/platforms/android/src/nl/xservices/plugins/Calendar.java:148: error: cannot find symbol
      if (PackageManager.PERMISSION_GRANTED != ContextCompat.checkSelfPermission(this.cordova.getActivity(), type)) {
                                                            ^
  symbol:   method checkSelfPermission(Activity,String)
  location: class ContextCompat
.../MyApp/platforms/android/src/nl/xservices/plugins/Calendar.java:157: error: cannot find symbol
      ActivityCompat.requestPermissions(
                    ^
  symbol:   method requestPermissions(Activity,String[],int)
  location: class ActivityCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

**Comment by EddyVerbruggen** [comment]
Are you building locally? Then run `android` from the command line and make sure your support tools/libs are up to date as `ContextCompat` is part of those libs.

**Comment by Zapmobilegames** [comment]
mhmh I suppose this should be an Intel XDK matter since I upload the project on theirs servers and they make the build for me, isn'it? Should I open a ticket on their forum?

**Comment by EddyVerbruggen** [comment]
Yes, seems to me they should update [this library](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/plugin.xml#L66) and/or build with the latest Android SDK.

**Comment by Ishanjn** [comment]
@EddyVerbruggen: I am using Apache Cordova Tool 8.1 with Visual Studio 2015 and i am still facing this issue with following error during build

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		D:\Ionic_Cordova_Applications\Dateme\Dateme\platforms\android\src\nl\xservices\plugins\Calendar.java:151: error: cannot find symbol	Dateme		1	
Error		 ^	Dateme		1	
Error		 symbol: method checkSelfPermission(Activity,String)	Dateme		1	
Error		 location: class ContextCompat	Dateme		1	
Error		D:\Ionic_Cordova_Applications\Dateme\Dateme\platforms\android\src\nl\xservices\plugins\Calendar.java:160: error: cannot find symbol	Dateme		1	
Error		 ActivityCompat.requestPermissions(	Dateme		1	
Error		 ^	Dateme		1	
Error		 symbol: method requestPermissions(Activity,String[],int)	Dateme		1	
Error		 location: class ActivityCompat	Dateme		1	
Warning		Note: Some input files use or override a deprecated API.	Dateme		1	
Warning		Note: Recompile with -Xlint:deprecation for details.	Dateme		1	
Error		2 errors	Dateme		1	
Error		FAILURE: Build failed with an exception.	Dateme		1	
Error		* What went wrong:	Dateme		1	
Error		Execution failed for task ':compileDebugJavaWithJavac'.	Dateme		1	
Error		> Compilation failed; see the compiler error output for details.	Dateme		1	
Error		* Try:	Dateme		1	
Error		Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.	Dateme		1	
Error		Error code 1 for command: cmd with args: /s,/c,"D:\Ionic_Cordova_Applications\Dateme\Dateme\platforms\android\gradlew cdvBuildDebug -b D:\Ionic_Cordova_Applications\Dateme\Dateme\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"	Dateme		1	
```
