### ISSUE TITLE
search event not working

### ISSUE THREAD

**Issue by zipif** [EddyVerbruggen/Calendar-PhoneGap-Plugin#267]
Hi,
my Event successfully created by the method " createEvent ", and i see it in the calendar.
but when I search the event buy it's name - no results on screen.
I test it in iphone 5 ios 7, and iphone 6S ios 9.2
thanks

**Comment by mnewmedia** [comment]
show some code..

**Comment by zipif** [comment]
I found the reason - events that taking place in more than a year, don't appear in the search results
