### ISSUE TITLE
i cannot get this plugin working

### ISSUE THREAD

**Issue by jomarocas** [EddyVerbruggen/Calendar-PhoneGap-Plugin#270]
i have time working in this, try this working but no success. any help, my procedure is the next

i create my project in this way

> cordova create calendar com.example.calendar calendar

> cordova platform add android

> cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git

add this line in index

> <script type="text/javascript" src="js/Calendar.js"></script>

and this is my index.html and the console.log working in enter but later no more, any more have ideas for this working, i try with phonegap app and cordova build android but no success any ideas? thanks

`<!DOCTYPE html>
<html>
  <head>
    <title>Device Ready Example</title>

    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" src="js/Calendar.js"></script>
    <script type="text/javascript" charset="utf-8">

    // Wait for device API libraries to load
    //
    function onLoad() {
        document.addEventListener("deviceready", onDeviceReady, false);
    }

    // device APIs are available
    //
    function onDeviceReady() {
        // Now safe to use device APIs
        console.log(device.cordova);
        alert('enter');
// prep some variables
  var startDate = new Date(2014,2,15,18,30,0,0,0); // beware: month 0 = january, 11 = december
  var endDate = new Date(2014,2,15,19,30,0,0,0);
  var title = "My nice event";
  var location = "Home";
  var notes = "Some notes about this event.";
  var success = function(message) { alert("Success: " + JSON.stringify(message)); };
  var error = function(message) { alert("Error: " + message); };

  // create a calendar (iOS only for now)
  window.plugins.calendar.createCalendar(calendarName,success,error);

  // delete a calendar (iOS only for now)
  window.plugins.calendar.deleteCalendar(calendarName,success,error);

  // create an event silently (on Android < 4 an interactive dialog is shown)
  window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,success,error);

  // create an event silently (on Android < 4 an interactive dialog is shown which doesn't use this options) with options.
  // The options support one option for now, but I will add more in the future:
  var calOptions = window.plugins.calendar.getCalendarOptions(); // grab the defaults
  options.firstReminderMinutes = 120; // default is 60, pass in null for no reminder (alarm)
  window.plugins.calendar.createEventWithOptions(title,location,notes,startDate,endDate,options,success,error);

  // create an event interactively (only supported on Android)
  window.plugins.calendar.createEventInteractively(title,location,notes,startDate,endDate,success,error);

  // create an event in a named calendar (iOS only for now)
  window.plugins.calendar.createEventInNamedCalendar(title,location,notes,startDate,endDate,calendarName,success,error);

  // find events
  window.plugins.calendar.findEvent(title,location,notes,startDate,endDate,success,error);

  // list all events in a date range (only supported on Android for now)
  window.plugins.calendar.listEventsInRange(startDate,endDate,success,error);

  // list all calendar names - returns this JS Object to the success callback: [{"id":"1", "name":"first"}, ..]
  window.plugins.calendar.listCalendars(success,error);

  // find all events in a named calendar (iOS only for now)
  window.plugins.calendar.findAllEventsInNamedCalendar(calendarName,success,error);

  // change an event (iOS only for now)
  var newTitle = "New title!";
  window.plugins.calendar.modifyEvent(title,location,notes,startDate,endDate,newTitle,location,notes,startDate,endDate,success,error);

  window.plugins.calendar.deleteEvent(newTitle,location,notes,startDate,endDate,success,error);
  alert(newTitle);
  alert('again enter');        
    }

    </script>
 `</head>
  <body onload="onLoad()">
    <h2>Device Ready Example</h2>
  </body>
</html>`

**Comment by jomarocas** [comment]
ok nothing here to help, i want help with this tutorial

the first you need to know, prior testing in android, your android is the best platform for try apps

install phonegap, i have version 5.4

you need begin the project with cordova create project

> cordova create calendar com.projectname.calendar calendar

> cordova platform add android

> cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git

- later go to folder www and call www2
- go to plugins/cordova-plugin-calendar/demo/ move www  and config.xml to principal folder in calendar/ replace all
- compile the app. the phonegap app no working with this, for compile make this

> cordova prepare

> cordova build android

maybe the app stay in this folder

> platforms/android/build/outputs/apk/android-debug.apk

 move this apk to your smartphone android, install and your test app works, i dont know if only works this, but for me working and this help a lot of people that question this

i upload the app here, and the file ready for prepare and compile

[calendar.zip](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/files/141325/calendar.zip)

**Comment by sphaso** [comment]
@jomarocas I've downloaded your app and followed the instructions, I still get "Class not found" when I click "Create Event". Any idea? Thanks!

**Comment by jomarocas** [comment]
@sphaso other functions of the app work? try download this app, install in your android device, and tell me if some wrong when you install the app
[calendar.apk.zip](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/files/146864/calendar.apk.zip)

**Comment by sphaso** [comment]
@jomarocas thank you, eventually I've figured it out. I've described the issue and the fix here: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/272
