### ISSUE TITLE
Creating an event with an alert!

### ISSUE THREAD

**Issue by dherre3** [EddyVerbruggen/Calendar-PhoneGap-Plugin#277]
Can we create a calendar event providing the option of reminding the user via alert a customizable period of time before the event occurs?, I did not find it in the documentation

Thank you!

**Comment by JohnRodney** [comment]
@dherre3 Aren't alert / reminders set on the calendar level?

**Comment by dherre3** [comment]
@JohnRodney Once you create an event using Cordova, there is an alert reminder of 60 minutes created by the cordova plugin by default. Therefore, you will get an alert one hour prior. Now, if you go in the Calendar and create an event manually, at least in iOS you can choose two alert reminders for an event in a customizable way. I am asking if there is such a functionality to set those alerts programmatically for an event created using the Cordova plugin, instead of the one hour alert it gives.

**Comment by JohnRodney** [comment]
I think thats what he is doing with the createEventWithOptions here?

```
var calOptions = window.plugins.calendar.getCalendarOptions(); // grab the defaults
calOptions.firstReminderMinutes = 120; // default is 60, pass in null for no reminder (alarm)
calOptions.secondReminderMinutes = 5;  

window.plugins.calendar.createEventWithOptions(title,eventLocation,notes,startDate,endDate,calOptions,success,error);
```

**Comment by dherre3** [comment]
@JohnRodney Yeah, I saw it right after you replied to me! I guess minutes is the best way to do it too.
Thank you John!

**Comment by taylormaster** [comment]
Hi!
This is not working with "`createEventInteractivelyWithOptions`", any idea?
