### ISSUE TITLE
cordova build android issue 'unexpected token'

### ISSUE THREAD

**Issue by grzesiekmq** [EddyVerbruggen/Calendar-PhoneGap-Plugin#281]
Hi I work with npm's plugin **cordova-plugin-calendar** and I get 'unexpected token' issue when type `cordova build android` . After debugging `cordova build -d` I get this message

> Executing "before_build"  hook for all plugins. Executing
> "before_prepare"  hook for all plugins. Error: SyntaxError: Unexpected
> token
>     at Object.parse (native)
>     at Function.PlatformJson.load (F:\win8 ja\OneDrive\Documents\magisterka IS\s 2\ZAI\projekt\cordova
> projekt\project\platforms\android\cordova\node_modules\cor
> dova-common\src\PlatformJson.js:35:21)
>     at new Api (F:\win8 ja\OneDrive\Documents\magisterka IS\s2\ZAI\projekt\cordo va
> projekt\project\platforms\android\cordova\Api.js:55:39)
>     at Object.getPlatformApi (C:\Users\Grzesiek\AppData\Roaming\npm\node_modules
> \cordova\node_modules\cordova-lib\src\platforms\platforms.js:59:23)
>     at C:\Users\Grzesiek\AppData\Roaming\npm\node_modules\cordova\node_modules\c
> ordova-lib\src\cordova\prepare.js:50:30
>     at Array.map (native)
>     at C:\Users\Grzesiek\AppData\Roaming\npm\node_modules\cordova\node_modules\c
> ordova-lib\src\cordova\prepare.js:48:39
>     at _fulfilled (C:\Users\Grzesiek\AppData\Roaming\npm\node_modules\cordova\no
> de_modules\q\q.js:787:54)
>     at self.promiseDispatch.done (C:\Users\Grzesiek\AppData\Roaming\npm\node_mod
> ules\cordova\node_modules\q\q.js:816:30)
>     at Promise.promise.promiseDispatch (C:\Users\Grzesiek\AppData\Roaming\npm\no
> de_modules\cordova\node_modules\q\q.js:749:13)

Here is my cordova project zip http://www29.zippyshare.com/v/UC2hmFXn/file.html

**Comment by EddyVerbruggen** [comment]
Similar to for instance [this error](http://stackoverflow.com/questions/31671450/cordova-build-android-and-ionic-build-android-results-in-syntaxerror-unexpecte), can't be related to this plugin.

**Comment by grzesiekmq** [comment]
thx for rapid response
