### ISSUE TITLE
Adding calendar events by looping through object array.., and a funny set of symptoms.

### ISSUE THREAD

**Issue by rhm13** [EddyVerbruggen/Calendar-PhoneGap-Plugin#283]
Hi guys,

So I'm trying to implement some sort of school diary application using the wonderful PhoneGap plugin.
The functionality I've implemented is temperamental at best (though I imagine that is down to my code and not the plugin, I'm not sure).

The problem is, when I loop through the object array (and pulling out relevant data to be put into the calendar event), my callBack methods are intermittently hit.

On my physical device (an iPhone 5S w/iOS 9.2.1), these callBacks are hit most of the time. However, on at least one of my looped elements, the following error shows:

_"{NSLocalizedDescription= "No calendar has been set";"_  

So, despite achieving to add **some** events, occasionally it seems to "forget" the calendar we're talking about and thus fails to add. I've provided the code, it's messy but rest assured that all the data being pulled out is sensible.

I'm looking to demo soon, so I'd really appreciate your help on this one.

Cheers!

`for (var i = 0; i < success.length; i++) {
                var event = success[i];

                var startYear = event.startDate.substring(0, 4);
                var startMonth = parseInt(event.startDate.substring(5, 7)) - 1;
                var startDay = event.startDate.substring(8, 10);

                var startHour = event.startDate.substring(11, 13);
                var startMinute = event.startDate.substring(14, 16);

                var endYear = event.endDate.substring(0, 4);
                var endMonth = parseInt(event.endDate.substring(5, 7)) - 1;
                var endDay = event.endDate.substring(8, 10);

                var endHour = event.endDate.substring(11, 13);
                var endMinute = event.endDate.substring(14, 16);

                var startDate = new Date(startYear, startMonth, startDay, startHour, startMinute, 00);
                var endDate = new Date(endYear, endMonth, endDay, endHour, endMinute, 00);

                $cordovaCalendar.createEventInNamedCalendar({
                    title: event.subject,
                    location: event.location,
                    notes: event.notes,
                    startDate: startDate,
                    endDate: endDate,
                    calendarName: 'School Diary'
                }).then(function (success) {
                    $ionicPopup.alert({
                        title: 'Success',
                        subTitle: 'Your event have successfully been updated!' + success,
                        cssClass: 'ionic-alert-box'
                    });
                }, function (error) {
                    $ionicPopup.alert({
                        title: 'Fail',
                        subTitle: 'There was an error while updating your calendar, please try again later.' + error,
                        cssClass: 'ionic-alert-box'
                    });
                });
            }`

**Comment by rhm13** [comment]
I should probably mention as well that the callBacks completely fail through the XCode Simulator..

**Comment by EddyVerbruggen** [comment]
You're mixing a promise with a for loop, right? So the second element in the for loop executes before the promise returns and your callbacks will be mixed up.

**Comment by rhm13** [comment]
I noticed this in the JS Console.., but couldn't find a solution. Is there a way I can stall the next iteration of the loop until the promise returns? I tried an ionic $timout, but it didn't seem to help..

**Comment by EddyVerbruggen** [comment]
Don't mix timeouts and promises. You'll regret that sooner or later.

So this becomes more of a [how do I uses promises and a for loop](http://stackoverflow.com/search?q=for+loop+promise) question. Click that link and look for an answer on SO.

**Comment by rhm13** [comment]
I’ve tried implementing promises.. this worked for a bit, but has since gone south. I don’t suppose you can see immediately what I’m doing wrong?


function addEvent(success) {
    var promises = [];

    for (var i = 0; i < success.length; i++) {
        var event = success[i];

        var startYear = event.startDate.substring(0, 4);
        var startMonth = parseInt(event.startDate.substring(5, 7)) - 1;
        var startDay = event.startDate.substring(8, 10);

        var startHour = event.startDate.substring(11, 13);
        var startMinute = event.startDate.substring(14, 16);

        var endYear = event.endDate.substring(0, 4);
        var endMonth = parseInt(event.endDate.substring(5, 7)) - 1;
        var endDay = event.endDate.substring(8, 10);

        var endHour = event.endDate.substring(11, 13);
        var endMinute = event.endDate.substring(14, 16);

        var startDate = new Date(startYear, startMonth, startDay, startHour, startMinute, 00);
        var endDate = new Date(endYear, endMonth, endDay, endHour, endMinute, 00);

        var pushToCal = $cordovaCalendar.createEventInNamedCalendar({
            title: event.subject,
            location: event.location,
            notes: event.notes,
            startDate: startDate,
            endDate: endDate,
            calendarName: 'School Diary'
        }).then(function (success) {

        }, function (error) {

        });
        promises.push(pushToCal);
    }
    return $q.all(promises);
}

On 13 Apr 2016, at 6:23 pm, Eddy Verbruggen <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #283<https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/283>.
