### ISSUE TITLE
ios return lastModified

### ISSUE THREAD

**Issue by mnewmedia** [EddyVerbruggen/Calendar-PhoneGap-Plugin#286]
Hey is it possible to return the lastModified Date on IOS?
```
@property(nonatomic, readonly) NSDate *lastModifiedDate
```
[apple docs](https://developer.apple.com/library/ios/documentation/EventKit/Reference/EKCalendarItemClassRef/index.html#//apple_ref/occ/instp/EKCalendarItem/lastModifiedDate)

IOS functions
- findEvent
- findEventWithOptions
- findAllEventsInNamedCalendar

**Comment by EddyVerbruggen** [comment]
Sounds good, are you up for a PR?

**Comment by mnewmedia** [comment]
I'm currently doing my (I don't know in english) end of it-school project/test, so no time for nothing at the moment. Also I have no idea of Objective-C, but I see a lot of plugins need help and there is no way around it. So I will learn it. But i think the first PR of me can come in about 2 weeks.

**Comment by EddyVerbruggen** [comment]
No worries, it was a very easy task thanks to the Apple doc you pointed me to. It's available now in the master branch of this repository for iOS.

Good luck graduating!

**Comment by mnewmedia** [comment]
oh you are quick =) very cool! thank you very much!
