### ISSUE TITLE
Find Event JSON.stringify

### ISSUE THREAD

**Issue by Danyzzz** [EddyVerbruggen/Calendar-PhoneGap-Plugin#287]
Hi Guys,
How can I parse a JSON.stringify(msg) result for retrieve a title message etc...

I have tried with this code but the result is undefined

`var obj = JSON.stringify(msg);
        alert(obj.id);
`

Thanks a lot.

**Comment by EddyVerbruggen** [comment]
Can you create a code sample with a bit more context? Also, perhaps you meant to use `JSON.parse(msg)` instead.

**Comment by Danyzzz** [comment]
This is a response:

`[{"id":"257","message":"Daniele this is a reminder","location":"","title":" andare a mangiare","startDate":"2016-04-21 20:00:00","endDate":"2016-04-29 09:00:00","allday":false},{"id":"258","message":"Daniele non dimenticare che alle 00:30 devi  lavare la macchina","location":"","title":" lavare la macchina","startDate":"2016-04-22 00:30:00","endDate":"2016-04-22 01:30:00","allday":false}]`

With JSON.parse(msg) there is this error:

`var obj = JSON.parse(msg);`
`alert(obj.id);`

Error in Success callbackId: Calendar1755348623 : SyntaxError: Unexpected token o

**Comment by EddyVerbruggen** [comment]
The response is an Array of JSON objects, not a JSON object - so try this instead:

```js
var json = [{"id":"257","message":"Daniele this is a reminder","location":"","title":" andare a mangiare","startDate":"2016-04-21 20:00:00","endDate":"2016-04-29 09:00:00","allday":false},{"id":"258","message":"Daniele non dimenticare che alle 00:30 devi lavare la macchina","location":"","title":" lavare la macchina","startDate":"2016-04-22 00:30:00","endDate":"2016-04-22 01:30:00","allday":false}];

alert("id: " + json[0].id);
```

I hope you agree this question shouldn't be in this repo as it's a general JS question. StackOverflow would be a better fit.
