### ISSUE TITLE
Cannot access plugin commands.

### ISSUE THREAD

**Issue by lipedeitos** [EddyVerbruggen/Calendar-PhoneGap-Plugin#288]
Hi, i have installed the plugin using the command:

phonegap local plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git --save
(tryed cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git --save too)

Then i run the command "phonegap serve" in my project, access it by my Samsung S5 (Android 5.0) i used console.log() on several plugins, like cordova.file, fileTransfer and many others, all of them return something, but on window.plugins.calendar.anyCommando it return something like:
"200 /socket.io/?EIO=3&transport=polling&t=LHYJHW4&sid=OU1lM9BjR1OMCNliAAAB"

Anyone any clue?

**Comment by EddyVerbruggen** [comment]
You need to test this plugin in a standalone app on a simulator or device. Through `phonegap serve` you can't interact with the native calendar. Until Google and Apple support access from a browser but that probably you and I will not witness this lifetime.
