### ISSUE TITLE
Calendar plugin along with Phonegap-Plugin-Push crashes the app in android.

### ISSUE THREAD

**Issue by Naveenbc** [EddyVerbruggen/Calendar-PhoneGap-Plugin#294]
Since both the plugin uses "com.android.support:support-v4:+" and push plugin updated this library usage to "com.android.support:support-v4:23+". If both these plugins are used together, in plugin.xml of both plugins should have similar <framework> tag for this library.

For example: change src="com.android.support:support-v4:+" to src="com.android.support:support-v4:23+" in plugin.xml of calendar plugin

**Comment by EddyVerbruggen** [comment]
The push plugin actually uses `<framework src="com.android.support:support-v13:23+" />` (13 instead of 4).. let me refresh my mind why Calendar needs the support lib again.

**Comment by EddyVerbruggen** [comment]
It's for permission handling. Currently implementing it differently to get rid of the support lib.

**Comment by EddyVerbruggen** [comment]
Please give the master repo a spin. It will give you version 4.5.0 which drops the support lib, and as a bonus now transparently handles Android M permissions. This means the permission related code can be removed from your calls to this plugin (although they still work as before). See the readme for details.
