### ISSUE TITLE
android vs ios

### ISSUE THREAD

**Issue by keenan35i** [EddyVerbruggen/Calendar-PhoneGap-Plugin#300]
window.plugins.calendar.findEvent( null, null,null, null, new Date('2017-06-17 19:00:00'),function(e){console.log(e)});

this works great on android however crashes ios, finds all events before the endDate on android.

**Comment by EddyVerbruggen** [comment]
What's the crash?

**Comment by keenan35i** [comment]
when i run it in ios 9 the entire app crashes

**Comment by EddyVerbruggen** [comment]
I mean the crashlog.

**Comment by EddyVerbruggen** [comment]
Two things to note after testing this:

- Passing in dates on iOS is mandatory for `findEvent` (this is undocumented though)
- The date you're passing in is not valid; try running `alert(new Date('2017-06-17 19:00:00'))` to see the error.

I may add support for finding events without dates but for performance reasons I've stayed far from it.
