### ISSUE TITLE
findEvent and createEvent not working for IOS

### ISSUE THREAD

**Issue by BramVM** [EddyVerbruggen/Calendar-PhoneGap-Plugin#317]
Hi, I inherited an old undocumented, unfinished project and i am trying to make it work. The project is made with angular and has a complicated nested build using tfs, npm, grunt, phoneghap/cordova. I should also note this is my first phoneghap/cordova project and i'm not even that good at angular jet so i spent weeks fixing all the bugs and errors. This is the last issue i need fixed to be able to release the project and i am getting desperate. While the Android build has no issues, nothing shows up in the IOS calendar when i use the _addCalendarItem function of the angular service shown below. 

While debugging i noticed the debugger never enters the success or error functions of "window.plugins.calendar.findEvent". I should also mention I don't even get any runtime errors when the function is called it just goes deeper and deeper (from calendar.js to cordova.js, there is no keeping track) until it just stops.

I am not sure why but everything in ".then("  after "_hasCalendarItem(calendarItem)" is skipped to. I suspect that it has something to do with the plugin or compatibility and not with angular or the code itself because the Android build works just fine.

I use cordova 6.0.3 for both builds.
The ios device I build and test on has IOS 9.3.3

Here is how i use the plugin:

var _hasCalendarItem = function(calendarItem){
    return $q(function(resolve,reject){
      if(!hasCalendarPlugin){
        console.log('calendar plugin not activated');
        reject('calendar plugin not activated');
      }else if(!calendarItem){
        console.log('no calendar item was provided');
        reject('no calendar item was provided');
      }else{
        window.plugins.calendar.findEvent(calendarItem.title,calendarItem.location,calendarItem.notes,calendarItem.startDate,calendarItem.endDate,function(result){
          resolve(result);
        },function(error){
          reject(error);
        })
      }
    });
  };

  var _addCalendarItem = function(calendarItem){
    return $q(function(resolve,reject) {
      _hasCalendarItem(calendarItem).then(function(){
        window.plugins.calendar.createEvent(calendarItem.title,calendarItem.location,calendarItem.notes,calendarItem.startDate,calendarItem.endDate,function(result){
          resolve(result);
        },function(error){
          reject(error);
        });
      },function(error){
        reject(error);
      })
    });
  };

**Comment by davidMGS** [comment]
My IOS kept closing when calling `findEvent` also.  What I had to do was ensure that startDate and endDate are not `null`.

**Comment by BramVM** [comment]
Thanks for the reply but i am afraid this is'nt the case for me. Here an exapmle readout of a calandar object i am using.

{title: "Introductie AIT & PPA tools ", notes: "<div><u>Doelgroep</u></div><div>Recruterende lijnmanager</div>", location: null, startDate: Wed Jun 01 2016 11:30:00 GMT+0200 (CEST), endDate: Wed Jun 01 2016 19:00:00 GMT+0200 (CEST)}

**Comment by dealancer** [comment]
+1

**Comment by BramVM** [comment]
Got it fixed by doing the folowing
 - changeng the build and using the npm version of the plugin instead.
 - ignored "notes" by passing undefined instead to findEvent .
(One of my notes contained line endings, the plugin seems not to be able to handel those. In my case, checking on the other properties was good enough)
