### ISSUE TITLE
open Calendar method crashes on iOS working on android fine.

### ISSUE THREAD

**Issue by shivenigma** [EddyVerbruggen/Calendar-PhoneGap-Plugin#323]
I am opening calendar with a specific date mentioned, the input to openCalendar method is a date object. It is working fine in android but it is crashing the app in iOS.

device : iphone63
os : iOS 9.3

**Comment by BramVM** [comment]
Have you tried other functions? I opend an issue for createEvent and findEvent but it seems none of the functions are working for me. Also when i made a test project with https://build.phonegap.com to test the plugin, it refused to build for ios after adding the latest version of the plugin to config.xml.

"Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: nl.x-services.plugins.calendar"

Here is the link to the issue i posted: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/317

**Comment by shivenigma** [comment]
yes other functions like findEvent are working fine for me, I am not using the phonegap build service but cordova local build. @BramVM

**Comment by EddyVerbruggen** [comment]
@BramVM Use the plugin [from npm](https://www.npmjs.com/package/cordova-plugin-calendar)

**Comment by shivenigma** [comment]
@EddyVerbruggen is there any suggestion you can give me?

**Comment by BramVM** [comment]
@EddyVerbruggen Linking the plugin from npm did the trick for my test project, thanks!

@shivenigma  I quickly tested adding an event and opening it afterwarts in this blank test project and it worked. Not sure if it's any help to you but here is what I did:

```
addCalendarEvent = function(){
    var startDate = new Date(2016,7,31,18,30,0,0,0); 
    var endDate = new Date(2016,7,31,19,30,0,0,0);
    var title = "My nice event";
    var location = "Home";
    var notes = "Some notes about this event.";
    var success = function(message) { };
    var error = function(message) { };
    window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,success,error);
    window.plugins.calendar.openCalendar(startDate, success, error);
}
document.getElementById("addCalendarEvent").addEventListener("click", addCalendarEvent);
```
I used: PhoneGap 6.3.0, cordova-plugin-calendar 4.5.1 and tested on an iphone 6 with IOS 9.2.1. Good luck!

**Comment by shivenigma** [comment]
I ignored the success and error callback as it is mentioned as optional in the docs. I guess that may be an issue, I'll check and let you know. Thanks for your time and kindness @BramVM

**Comment by EddyVerbruggen** [comment]
@shivenigma Can you share the crashlog perhaps?

**Comment by shivenigma** [comment]
2016-08-31 11:43:47.394 Surprise You Later[477:80338] -[NSNull doubleValue]: unrecognized ```
selector sent to instance 0x3a5999e0
2016-08-31 11:43:47.394 Surprise You Later[477:80338] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull doubleValue]: unrecognized selector sent to instance 0x3a5999e0'
*** First throw call stack:
(0x23925b0b 0x230e2dff 0x2392b455 0x239290ab 0x23853298 0xb763f 0x968ba7 0x974eff 0x9747f1 0x23656e0d 0x236569fc)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

@EddyVerbruggen  the above is the log. Am I supposed to pass a timestamp with milliseconds? I saw something like below
`NSTimeInterval _startInterval = [date doubleValue] / 1000; // strip millis
`
though I am not familiar with iOS native development this seemed to me like I need to pass timestamp.

**Comment by EddyVerbruggen** [comment]
This should suffice (just confirmed on the latest version):

```js
var d = new Date(2016,7,30);
window.plugins.calendar.openCalendar(startDate, onSuccess, onError);
```

Which plugin version are you using?

**Comment by shivenigma** [comment]
Yeah I used the same kinda thing. But for some reason it was returning invalid date in iOS, I then fixed it using momentjs to construct date object now it works fine. Thanks.

**Comment by yogendrakarekar** [comment]
@shivenigma what exactly you did, please explain
