### ISSUE TITLE
callback.success.apply is not a function

### ISSUE THREAD

**Issue by robersant** [EddyVerbruggen/Calendar-PhoneGap-Plugin#328]
Hi, I tried to test some of the examples, and it gives me the following error:

![image](https://cloud.githubusercontent.com/assets/5558586/18523867/7c4f6fb2-7a8c-11e6-97af-ecfa439e854b.png)

Im using it with Cordova CLI version 6.2.0 and the version of the plugin is 4.5.1

Does anyone have the same issue? Thanks!

**Comment by EddyVerbruggen** [comment]
Please ask generic Cordova/JS questions on StackOverflow to reach a broader audience.
