### ISSUE TITLE
iOS 9 intermittent adding of silent events

### ISSUE THREAD

**Issue by andreyavram** [EddyVerbruggen/Calendar-PhoneGap-Plugin#330]
Hello,

First, thanks for this awesome plugin!

Secondly, we have some strange issues while using this plugin on iOS 9.(not tested yet on iOS 10)
On version 4.5.1 (haven't tested yet 4.5.2, but I didn't notice any changes for iOS anyway), the adding of events, silently, seems to work only for a few times, then it just silently fails, no success or failure callbacks.

This gave us a lot of headaches trying to pinpoint a specific case, but we haven't found one, although  other developers that we reached out, managed to reproduce it.

In our app we are adding a dozen events in the calendar, and we noticed that only the first 1-2 get added. Then we tried from the console, to manually run the example code, and we noticed the same behaviour. After starting the app again it seems to work again for a few events.
This is with or without specifying a calendar (name & id). The app or plugin don't crash.

Any thoughts on this? 
 
Thanks!

**Comment by EddyVerbruggen** [comment]
You need to wait for the success callback to return before invoking the create function again.

**Comment by andreyavram** [comment]
I've waited, it's not that for sure. The described behaviour occurs even when just manually running a few times the example, after a few added events, it won't add anymore.

**Comment by EddyVerbruggen** [comment]
Can you post the exact code that causes this issue please?

**Comment by andreyavram** [comment]
Hi,
This piece of code is runned in the console, in the safari inspector of the app, to ensure no other influence. 
The plugin is correctly loaded as I can see in the window.plugins.calendar object.
No callbacks get called when running this. (Now I tested on iOS 10.0.1)
The callOptions object is populated correctly.

```javascript
var startDate = new Date(2016,8,21,18,30,0,0,0); // beware: month 0 = january, 11 = december
  var endDate = new Date(2016,8,21,19,30,0,0,0);
  var title = "My nice event";
  var eventLocation = "Home";
  var notes = "Some notes about this event.";
  var success = function(message) { console.log("Success: " + JSON.stringify(message)); };
  var error = function(message) { console.log("Error: " + message); };
  
 var calOptions = window.plugins.calendar.getCalendarOptions(); // grab the defaults
  calOptions.firstReminderMinutes = 120;
 
 window.plugins.calendar.createEventWithOptions(title,eventLocation,notes,startDate,endDate,calOptions,success,error);
```

**Comment by EddyVerbruggen** [comment]
Looks legit. So how do you loop this code to create multiple events?

**Comment by andreyavram** [comment]
That's the thing, not even this simple case doesn't work. 
I suspect that it might be some kind of plugins conflict, although not sure how that could be possible.. I figured that out by having a temporary error due to the new CSP policy in ios 10, when gap://ready was blocked, and although cordova didn't fire the ready event, the calendar plugin was available and it seemed to work perfectly. Now after fixing the CSP and the cordova events fire correctly, I can't seem to get it working again. My list of plugins is below, is there any know conflict that you are aware of? I didn't find anything useful so far.  If it matters, I'm using Ionic 1.

cordova-plugin-apprate 1.1.7 "AppRate"
cordova-plugin-calendar 4.5.3 "Calendar"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-globalization 1.0.2 "Globalization"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-restrict-keyboard 1.0 "Restrict Keyboard"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-toast 2.2.1 "Toast"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.email-composer 0.8.2 "EmailComposer"
de.appplant.cordova.plugin.local-notification 0.8.2 "LocalNotification"
ionic-plugin-keyboard 2.0.1 "Keyboard"
phonegap-plugin-push 1.6.1 "PushPlugin"

**Comment by EddyVerbruggen** [comment]
I don't think it's a conflict as there are no external dependencies in this plugin. Btw, "EmailComposer" is listed twice with different versions.

Can you provide a simple, complete example which I can drop in a vanilla Cordova CLI helloworld project that reproduces this issue?

**Comment by andreyavram** [comment]
Well.. it seems that in blank ionic app, with just the default plugins and the calendar plugin, it works fine(running the code posted above in the app inspector).
I can't seem to find any reason why it won't work, in my app, the plugin is loaded correctly, and I run the code above in directly the app's inspector..

**Comment by andreyavram** [comment]
Hi again,

Although, like I said it seems to work on iOS 10, including in my app after some cleanup, the callbacks don't get called on iOS, not even in the blank app.
I attached here a simple app, that just adds an event, and should spit in the console the output from the callbacks.
[calendarApp.zip](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/files/491061/calendarApp.zip)

**Comment by EddyVerbruggen** [comment]
@andreyavram If it works in a blank Ionic app but there's a problem in your own, then why would this be something for me to fix? And if you really think it's a problem with the plugin then please attach the platforms/ios folder so I can simply open it in Xcode and debug it.

**Comment by andreyavram** [comment]
I didn't want you to fix my app :), maybe I expressed myself poorly, sorry.
I was just saying that with the latest version and ios 10 it seems to add events fine, even in my app.

But in the attached blank app, altough it adds events, the callbacks are not getting called at all, and that I think it might be a problem with the plugin itself.

https://www.dropbox.com/s/2d7e9hxkxf7kyp9/calendarApp.zip?dl=0

**Comment by EddyVerbruggen** [comment]
Thanks for the demo app. I deployed it to an iPhone 6s simulator running iOS 9.1, pressed the 'new event' button 9 or 10 times and got this in my Calendar:

![simulator screen shot 28 sep 2016 20 36 38](https://cloud.githubusercontent.com/assets/1426370/18927205/3f8ff9b8-85bb-11e6-9eb5-2bdacfb7c81b.png)

Same on iPhone 7 (iOS 10) simulator, also the console logs the stuff of the success callback fine (thanks to the fact you've added the cordova-plugin-console plugin):

2016-09-28 20:38:43.194 calendarApp[15696:2436493] Success: "82141663-44D6-4198-A5FB-894877D2784B"
2016-09-28 20:38:44.346 calendarApp[15696:2436493] Success: "5BA278C9-96A1-4DF0-A3BD-FF7F5E241244"

So yeah... looks good, right?

**Comment by andreyavram** [comment]
Sure, it looks good!
But to be honest, I didn't test it on the simulator, just on the device, iPhone 6s. Will give it a try on the simulator as well.

**Comment by andreyavram** [comment]
It seems that the waiting for callback logic was not ok in my project, and on iOS, once the plugin silently crashes (if you send the events too quickly), it won't work again until you restart the app.
Thanks for the help!
