### ISSUE TITLE
Android 6.x nothing works

### ISSUE THREAD

**Issue by eparlier** [EddyVerbruggen/Calendar-PhoneGap-Plugin#339]
findEvent doesn't find anything
addEvent never fires success event, in all flavours
Can someone confirm? Thanks.

**Comment by PriyankaRose** [comment]
yes, for me too nothing happens...
Did you figured any solution?

**Comment by jimmy-tfp** [comment]
findEvent is working here on a Nexus 7 running 6.0.1

**Comment by eparlier** [comment]
@PriyankaRose nope, been hoping for an answer from Eddy

**Comment by EddyVerbruggen** [comment]
What have you tried already?

**Comment by eparlier** [comment]
@EddyVerbruggen 
```
window.plugins.calendar.createEvent('test', null, null, new Date('2016','11','11','10','0','0'), new Date('2016','11','11','11','0','0'), null, addSuccess, addError);	
function addSuccess(__msg){
	console.log('event added success', __msg);
}
```

addSuccess or addError are never fired.

```
window.plugins.calendar.findEvent('test', null, null,  new Date('2016','10','01'), new Date('2016','10','31'), listSuccess, listError);

function listSuccess(__msg){
	console.log(__msg);
}
```

listSuccess never fired.

**Comment by EddyVerbruggen** [comment]
Oh, and why does that one work now and didn't before?

You may want to add an `window.onerror` catch-all method to make sure there are no JS errors.

**Comment by eparlier** [comment]
I did not test listEvents properly. I've retested everything, listing works, but no callback on adding an event.

**Comment by EddyVerbruggen** [comment]
@eparlier you code has a `null` where the startdate is expected; remove the last `,null ` from this line:

```js
window.plugins.calendar.createEvent('test', null, null, new Date('2016','11','11','10','0','0'), new Date('2016','11','11','11','0','0'), null, addSuccess, addError);
```

**Comment by eparlier** [comment]
Oh god this is monday am... You are right, apologies for this mess.
