### ISSUE TITLE
warning: incompatible pointer types assigning to 'EKEvent *' from 'EKCalendarItem *' [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by barkoczi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#343]
Hi there, 

while build the cordova ios app, I receive the following warning:
```
Plugins/cordova-plugin-calendar/Calendar.m:156:20: warning: 
      incompatible pointer types assigning to 'EKEvent *' from 'EKCalendarItem *' [-Wincompatible-pointer-types]
          theEvent = [self.eventStore calendarItemWithIdentifier:calEventID];
```
Then the app crashes at any function of plugin. 

Any idea?

**Comment by EddyVerbruggen** [comment]
That should not be related to a crash really. Are you sure it has a correlation with this warning?

**Comment by barkoczi** [comment]
Sorry, the problem was caused by some messy string from back-end and tried to put into calendar as notes. Please close this ticket. The plugin works well.

**Comment by barkoczi** [comment]
I am not sure, but if the latest version of this plugin is present in my
app, it immediately crash if any function of plugin invoked.
