### ISSUE TITLE
iOS - Application crash while getting events from a Calendar

### ISSUE THREAD

**Issue by antandbuffalo** [EddyVerbruggen/Calendar-PhoneGap-Plugin#350]
iOS - Application crash while getting events from a Calendar using the function "findEventWithOptions" 
The fix is need to initialise theEvent to nil.
In Calendar.m,
change line 821 from 
EKCalendarItem *theEvent;
to 
EKCalendarItem *theEvent = nil;

it is working fine.

**Comment by EddyVerbruggen** [comment]
Looks good, added it.
