### ISSUE TITLE
Question: URL schema

### ISSUE THREAD

**Issue by natanraj** [EddyVerbruggen/Calendar-PhoneGap-Plugin#351]
hi Eddy, Does it have facility to create options as URL into calendar ? I am looking to deeplink the calendar event to my app. Hence this query.

**Comment by EddyVerbruggen** [comment]
Search for url in the readme.

**Comment by natanraj** [comment]
Sorry, if I wasn't clear. I wanted to see if we can give **custom link** into notes etc upon clicking which it can open / deeplink another app. i used URL already, it just provided that as a textual notes without any action/event fired.

**Comment by EddyVerbruggen** [comment]
Are you able to get what you want by manually entering it in the notes? If that works, the plugin should be able to do the same.

**Comment by natanraj** [comment]
You are right. I dont think the calendar widget provides any other event/action except on 'location' key.
