### ISSUE TITLE
"Notes" description gets reflected in URL field in iOS calendar

### ISSUE THREAD

**Issue by karanbalkar** [EddyVerbruggen/Calendar-PhoneGap-Plugin#355]
Hi,

I am using the below code to create an event

 // prep some variables
  var startDate = new Date(2015,2,15,18,30,0,0,0); // beware: month 0 = january, 11 = december
  var endDate = new Date(2015,2,15,19,30,0,0,0);
  var title = "My nice event";
  var eventLocation = "Home";
  var notes = "Some notes about this event.";
  var success = function(message) { alert("Success: " + JSON.stringify(message)); };
  var error = function(message) { alert("Error: " + message); };

// create an event silently (on Android < 4 an interactive dialog is shown)
  window.plugins.calendar.createEvent(title,eventLocation,notes,startDate,endDate,success,error);

This creates the event with the "Notes" value properly filled in Android. However, the same when tried on iOS, populates the "Notes" value into the URL field of the calendar.
 
How to solve this issue?

Regards,
Karan

**Comment by EddyVerbruggen** [comment]
Can't reproduce. Please post a screenshot / video if it's still happening.
