### ISSUE TITLE
openCalendar function not available iOS

### ISSUE THREAD

**Issue by billycomic** [EddyVerbruggen/Calendar-PhoneGap-Plugin#356]
![screen shot 2016-12-21 at 4 50 38 pm](https://cloud.githubusercontent.com/assets/13626591/21409219/97423200-c79e-11e6-9763-7c33371fe3e7.png)
I'm trying to open the calendar from a function call and it's not showing up when I inspect the $cordovaCalender object or the window.plugins.calendar.openCalendar(); 

I see it in the calendar.js file, and in the .h and .m files, but it is not showing up. Can you tell me how to get that method to pull back?

**Comment by billycomic** [comment]
I only need to open the calendar so the user can delete all instances of an event that contains a specific message. So, if a user created a repeating event that contained the same "notes", then when I delete, i want to delete all occurences of the event that contains that same "notes" value. Is that possible with the plugin in its current state?

**Comment by EddyVerbruggen** [comment]
That's not a problem of this plugin; you're using Ionic Native / ng-cordova as a wrapper of this plugin. So please send a PR to their repo to add support for this feature.

**Comment by billycomic** [comment]
I saw that after I submitted the issue. I added it to the calendar.js that contains the angular injection and it is now available. Thanks.
