### ISSUE TITLE
many createEvent not working on iOS

### ISSUE THREAD

**Issue by ursmeier-mercatus** [EddyVerbruggen/Calendar-PhoneGap-Plugin#358]
I am subscribing to a firebase list to get the dates for which we have to create calendar entries.
Plugin 4.5.5
Ionic2 rc4

Android: OK

iOS: 
Basically iOS works, if just call createEvent(..), so I don't think it is a setup problem.
Nothing happens, if createEvent(..) is called in a subscription (see example below).
createEvent is not executed, then/catch is not called. 
Any hints?

Code example:
this.dataService.ratingDates$.subscribe(ratingDates => {
   ratingDates.map(ratingDate) => {
       Calendar.createEvent(....)  // creates no entry on iOS
       .then(() console.log(...))   // never called
       .catch(() console.log(...)) // never called
   })
})

**Comment by ursmeier-mercatus** [comment]
Tracked it further. It is related to the fact, that I am creating many events. 
Tested both createEvents individually. They work.
Two createEvents in a row do not work. No error.

Has anybody successfully created many events on iOS?

Example, which does **not** work:
    Calendar.createEvent("Event 1", "Location", "notes", new Date(2017, 1, 1, 13), new Date(2017, 1, 1, 14))
     .then(result => {
       console.log("1 create event success: ", result);
       })
       .catch(error => {
         console.log("1 create event error: ", error)
       })

   Calendar.createEvent("Event 2", "Location", "notes", new Date(2017, 1, 1, 15), new Date(2017, 1, 1, 16))
      .then(result => {
        console.log("2 create event success: ", result);
      })
      .catch(error => {
        console.log("2 create event error: ", error)
      })

**Comment by ursmeier-mercatus** [comment]
Just tested if chaining works and it does.
Calendar.createEvent("Event1"....).then(() => Calendar.createEvent("Event2"....) 

I think it is an implementation problem because the code is not re-entrant.
@EddyVerbruggen how can I submit this as a bug?

**Comment by EddyVerbruggen** [comment]
@ursmeier-mercatus If you search the issues in the repo you'll find more ppl having trouble creating multiple events. There is no plugin method `createEvents`, rather `createEvent` and you'll need to wait for it to finish before calling it again as you found out.

If that needs to change open a PR and I'll be happy to review it. If you don't dare touching the native code you could opt for passing an array of events to a new `createEvents` function and loop through those events in the [JavaScript bridge](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/www/Calendar.js). Of course JS needs to wait for the previous call to native to complete in order to prevent this issue. Perhaps later we can push it to native and perhaps even make that code multithreading-safe.

**Comment by ursmeier-mercatus** [comment]
Thanks @EddyVerbruggen for taking the time to clarify and confirming. Really appreciated.
Since I was unable to find the other issues, a small hint in the readme could prevent others to find it out the hard way.

Knowing the issue, the simplest solution might be a recursion over the then-chain

{
// get the dates 
...                           this.af.database.list(`/${this.groupRatingsDatesRef}/${groupKey}`).subscribe(ratingDates => {
                                if (ratingDates.length > 0) {
                                    this.addToCalendar(ratingDates, groupname, calendarOptions);
                                }
...
}

   private addToCalendar(ratingDates: any[], groupname: string, calendarOptions: any) {
        let ratingDate = ratingDates.pop();
        let eventDate = new Date(ratingDate.dueDate); 
        Calendar.createEventWithOptions(`"${groupname}" rating`, '', 'Group Rating', eventDate, eventDate, calendarOptions)
// chain with recursion
            .then(() => {
                if (ratingDates.length > 0) {
                    this.addToCalendar(ratingDates, groupname, calendarOptions);
                }
            })
    }

**Comment by pinpointpanda** [comment]
@ursmeier-mercatus thanks for sharing that idea.

I arrived at a similar conclusion when trying to add multiple events, but wasn't sure about recursion chaining the 'thens'. Did you implement this in the end? How did you manage the error handling?

**Comment by ursmeier-mercatus** [comment]
Yes, I did implement it. The error handling is done by just catching errors and exiting the recursion.

I ran into a similar issue with file writing. Which I solved by using the array reduce method. This would also work with the calendar, if you have an array of objects to be saved.
e.g.
```
    private writeCSVFile(ratings: any[]): Promise<any> {
        // run sequentially to prevent File to overwrite itself
        return ratings.reduce((p, rating) => {
            return p.then(() => {
                return File.writeFile(cordova.file.dataDirectory, 'filename.csv‘, `${rating.groupname};${rating.currentGroupname};\n`, { append: true })
            })
        }, Promise.resolve());
    }

```
This chains the promises (p) from File.writeFile which eases error handling.
To start it uses a first resolved promise with Promise.resolve().

Hope this helps.

**Comment by pinpointpanda** [comment]
That's clever - I'll have a crack at this approach later.
Thanks for sharing :)

**Comment by pinpointpanda** [comment]
@ursmeier-mercatus thanks a bunch for sharing that.
Works like a charm for adding multiple events, which I already had stored in an array anyway. Very elegant.

```
  createRepeatEvents(events: EventModel[]): Promise<any> {

    return events.reduce((p, event)  => {
      return p.then(() => {
        return this.calSvc.addEvent(event).catch((err)=> {
          console.error(err);
        });
      })
    }, Promise.resolve());

  }
```

**Comment by plannie-nezer** [comment]
Using recursion solved it for me
