### ISSUE TITLE
would you like to add displayname field to listCalendar()?

### ISSUE THREAD

**Issue by seducer0719** [EddyVerbruggen/Calendar-PhoneGap-Plugin#359]
right now listCalendar() return with id and name fields , however from my side i can only get the name value when the app running under AOSP androids. for some other android the name always return empty. 
however, i saw there is a field for calendar named as displayname in createCalendar(), so would you like to add this **displayname** in to listCalendar()?

below code is what i found in createCalendar(), the displayname having same value as name
```
      // doesn't exist yet, so create

      cv.put(CalendarContract.Calendars.NAME, calendarName);
      cv.put(CalendarContract.Calendars.CALENDAR_DISPLAY_NAME, calendarName);

```

**Comment by EddyVerbruggen** [comment]
Would you be willing to do a PR?

**Comment by seducer0719** [comment]
sure.... i just did

**Comment by EddyVerbruggen** [comment]
Thx!
