### ISSUE TITLE
Class not found in android 

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/Calendar-PhoneGap-Plugin#4]
Hi and thanks for this plugin

I'm trying to use this plugin in my app (using phonegap build 2.9) and under ios 7 works perfect, but when I try to use it under android (4.2.2 in my tests) i got the error: "class not found".

I'm using this line (acording the documentation) window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,success,error);

Any idea about this issue?

**Comment by sphaso** [comment]
@EddyVerbruggen hi, I'm having the same issue. How would I use your sample project? I don't seem to be able to build it (Not a Cordova Project?).
