### ISSUE TITLE
Create event stops working on iOS

### ISSUE THREAD

**Issue by nevills** [EddyVerbruggen/Calendar-PhoneGap-Plugin#402]
After an X amount of create events on iOS it stops pushing them into the agenda. All is working fine before but it just stops adding them. Has anyone encountered this before?

**Comment by EddyVerbruggen** [comment]
Depends on how you add them. Wait for the callback before adding another one.

**Comment by nevills** [comment]
So this could be the fix?
https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/358

**Comment by EddyVerbruggen** [comment]
If you're currently trying to simultaneously create the events then yes.
