### ISSUE TITLE
createEventInteractively doesn't request for permissions

### ISSUE THREAD

**Issue by marcRDZ** [EddyVerbruggen/Calendar-PhoneGap-Plugin#403]
Hello

Firstly, thanks for that useful plugin and congratulations for your work.

I just realize that 'createEventInteractively()' lacks of this piece of code that is present in all others methods in the class Calendar.java:

`    if (!calendarPermissionGranted(Manifest.permission.WRITE_CALENDAR)) {
      requestWritePermission(PERMISSION_REQCODE_CREATE_EVENT);
      return;
    }`

I don't know if it's the expected situation in your design, but if someone like me wants to call directly this method without calling 'createEvent' previously or another one thats grants permissions, the app will crash.

Thanks again

**Comment by EddyVerbruggen** [comment]
Did you verify that is the case?

**Comment by marcRDZ** [comment]
Well, I'm testing my app in a Android 7.0 device and I think so.
Test Case:
 1. Install and first run
 2. Register user
 3. Make an appointment
 4. Click on 'Save Event' (that calls 'createEventInteractively()')
Expected result: App ask for permissions and/or save event.
Obtained result: App crash and device ask to send bug report
Maybe I would have to test it more times but after modifying your code it's working as expected.

**Comment by EddyVerbruggen** [comment]
I'm surprised `createEventInteractively` requires the permission, but if that's the case then it needs to change indeed.

**Comment by marcRDZ** [comment]
I don't understand, do you surprise because in previous Android versions is not needed? I don't know as I didn't work with calendar previously. Maybe is a change in Nougat version.

**Comment by EddyVerbruggen** [comment]
The interactive option switches to the Calendar app, so I'm surprised your app needs permission to create an event. Anyway, if that's what it is then the permission check needs to be added.

**Comment by marcRDZ** [comment]
No, wait!!
I'm sorry. You are right.
I'm working in two apps. One of them uses your plugin directly and it works as expected. The one that fails has custom code in the createEventInteractively method, I don't understand why it fails as I only modify the args in JsonArray before put in calIntent extras but it works if I request for permissions. I don't like that but is not my project.
Excuse me, I don't pretend to waste your time. You can close this issue.

**Comment by EddyVerbruggen** [comment]
No worries, good luck! 👍
