### ISSUE TITLE
Android Only: "createEventInteractivelyWithOptions" success callback return message "OK"

### ISSUE THREAD

**Issue by sonlexuan** [EddyVerbruggen/Calendar-PhoneGap-Plugin#421]
In Android, when I using createEventInteractivelyWithOptions, Calendar Legacy Add Event window does appear. But even I click on "Cancel" button, the success callback return message "OK" although I did cancel adding this event.
This not happens in IOS.
Could anyone help me fix this?
Thank you.

**Comment by sonlexuan** [comment]
Sorry :D 
After a few minutes reviewing your code, I actually fixed this thing.
Could I close this now? :D

**Comment by tobeee** [comment]
What was the solution to this?

**Comment by nitishbhardwaj1111** [comment]
@EddyVerbruggen i am also getting this issue, can you please tell me the solution.

**Comment by FrancescoPaiola** [comment]
I have the same problem

**Comment by Abaddon-88** [comment]
check with findEvent methode if event was created or not
