### ISSUE TITLE
createEventInteractivelyWithOptions with calendarId on Android doesn't work

### ISSUE THREAD

**Issue by hobzcalvin** [EddyVerbruggen/Calendar-PhoneGap-Plugin#427]
Setting `calendarId` on the calendar options object passed to `createEventInteractivelyWithOptions` doesn't work on Android: The calendar app opens as expected, but the last-used calendar is selected instead of the one specified. I made sure the `calendarId` was the result of the `listCalendars` method. [This StackOverflow](https://stackoverflow.com/a/36160480/1883624) suggests it isn't possible to specify a calendar with an Intent. If not, the documentation should be updated to note this limitation.

**Comment by EddyVerbruggen** [comment]
OK, feel free to change that with a PR 👍
