### ISSUE TITLE
can't create events in a for loop 

### ISSUE THREAD

**Issue by sgs1** [EddyVerbruggen/Calendar-PhoneGap-Plugin#428]
Hi everybody!

I have some difficulties to create an event in a For cycle.
This is my 

> var db = null;
    db = window.sqlitePlugin.openDatabase({name: 'imfige.db', location: 'default'});
    db.transaction(function (tx) {
        var query = "SELECT * FROM appuntamenti";

    

>  tx.executeSql(query, [], function (tx, resultSet) {
           console.log('resultSet.rowsAffected: ' + resultSet.rowsAffected);

           

> for(var i = 0; i < resultSet.rows.length; i++)
           {
               console.log("Città : " + resultSet.rows.item(i).citta + " titolo : " + resultSet.rows.item(i).title);
               //myLocationcoordinates[i] = res.rows.item(i).Coordinates;
               // Salviamo tutto nel calendario
               var startDate = new Date(2015,2,15,18,30,0,0,0); // beware: month 0 = january, 11 = december
 var endDate = new Date(2015,2,15,19,30,0,0,0);
 var title = "My nice event";
 var eventLocation = "Home";
 var notes = "Some notes about this event.";
 var success = function(message) { alert("Success: " + JSON.stringify(message)); };
 var error = function(message) { alert("Error: " + message); };
 window.plugins.calendar.createEvent(title,eventLocation,notes,startDate,endDate,success,error);  }

> },
        function (tx, error) {
            console.log('SELECT error: ' + error.message);
        });
    }, function (error) {
        console.log('transaction error: ' + error.message);
    }, function () {
        console.log('transaction ok');
    
    });

 
In the for cycle, I've typed the example code because with the mine, I have the same problem.
I don't see the event in the local calendar. And it's very strange, because normally it works without problems.
I'm using 4.5.0 version on Ios 11. Same problem on Ios 9.

Someone has a solutions? Sorry for the bad formatting.

**Comment by EddyVerbruggen** [comment]
Yeah don't use a loop.. the create function is async, so use promises for instance. There are similar issues in this repo.

**Comment by sgs1** [comment]
Can you make an example? I've found some issues, but I'm using cordova and not Ionic, so I'm in difficulty.
