### ISSUE TITLE
Android all day event

### ISSUE THREAD

**Issue by edvenkat** [EddyVerbruggen/Calendar-PhoneGap-Plugin#432]
How to set all day event with createEventWithOptions

is possible ???

please advice

**Comment by vinaygiri** [comment]
are you got any solution??

**Comment by edvenkat** [comment]
@vinaygiri try this code

var calOptions = window.plugins.calendar.getCalendarOptions();
calOptions.allday = true;
window.plugins.calendar.createEventWithOptions(title, loc, notes, startDate, endDate, calOptions, function(){},function(){})

**Comment by vinaygiri** [comment]
thank you,  i will try this

**Comment by vinaygiri** [comment]
I tryed but not displaying "allday" below the event name.

Its showing 00:00

Please help me

**Comment by edvenkat** [comment]
could you please share the code

**Comment by vinaygiri** [comment]
Thank u for reply

This is what i am using to insert recurring event in android native calendar and i also tried with 1 day add to enddate but that is also not working

This code displays 00:00 and if i add 1day to end date its displays 00:00 - 00:00

var title = "testevent";
                var eventLocation = "";
                 var notes = "test"; 
var startDate =Mon Dec 25 2017 00:00:00 GMT+0530 (IST)
var endDate = Mon Dec 25 2017 00:00:00 GMT+0530 (IST)

calOptions.recurrence =true;
calOptions.allday = true;

window.plugins.calendar.createEventWithOptions(title,eventLocation,notes,startDate,endDate,calOptions,success,error);

Please help me

**Comment by vinaygiri** [comment]
Thank u i got result
