### ISSUE TITLE
window.plugins.calendar.modifyEventWithOptions not working in Android

### ISSUE THREAD

**Issue by vinaygiri** [EddyVerbruggen/Calendar-PhoneGap-Plugin#436]
Hi 

window.plugins.calendar.modifyEventWithOptions() is not working in android, giving ""Invalid action" error, I am not getting what is wrong, because its working in IOS. 
Please help me regarding this,thank u.

**Comment by EddyVerbruggen** [comment]
See the table in the readme. It’s not supported on Android.

**Comment by vinaygiri** [comment]
Is there any way to do that, or any other plugin

**Comment by EddyVerbruggen** [comment]
I'm not aware of any other plugin doing that. This one could be extended to support it of course, but it doesn't have priority for me.
