### ISSUE TITLE
Cannot Compile on CLI 7.0.1

### ISSUE THREAD

**Issue by aesculus** [EddyVerbruggen/Calendar-PhoneGap-Plugin#437]
PGB requires us now to be on CLI 7.0.1 and when I add the calendar plugin I get these errors on compile:
`<plugin name="cordova-plugin-calendar" source="npm">`

When compiled I get this error: 
`Installing "cordova-plugin-calendar" at "5.0.0" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.3, failed version requirement: >=6.3.0
Skipping 'cordova-plugin-calendar' for android`

Is there a version number I can include in the plugin that will work?

**Comment by edvenkat** [comment]
Try this

add version 4.6.0....
```
<plugin name="cordova-plugin-calendar" source="npm" spec="4.6.0">
   <param name="CALENDAR_USAGE_DESCRIPTION" value="xxxxxx" />
</plugin>

```

**Comment by aesculus** [comment]
That seemed to have done the trip. Thank you.
