### ISSUE TITLE
npmjs latest version

### ISSUE THREAD

**Issue by Maziar-Fotouhi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#438]
Currently the latest version in npm repository has been changed to 5.0.0 but no change logs are provided on the repo.
https://www.npmjs.com/package/cordova-plugin-calendar
I am not sure if this is intentional or not, so I am creating this issue.
@EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Thank you. Will sort that out with the next one.
