### ISSUE TITLE
All day event not being displayed as all day event on android

### ISSUE THREAD

**Issue by Simbaclaws** [EddyVerbruggen/Calendar-PhoneGap-Plugin#443]
When I create a allday event using 0:00 as start time on for example january the 1st and 0:00 as end time on january the 2nd. The event is still displayed on android's calendar as an event that starts from 0:00 january the 1st till 0:00 january the 2nd, and doesn't display as an all day event but as a regular one. (the toggle button inside android's calendar allday event doesn't switch to on). I haven't tested this yet for iOS.

Is it possible to have a calendarOption of turning the allday event to true or false just like the toggle button?

**Comment by vinaygiri** [comment]
calOptions.allday = true;

use this, for me it worked

**Comment by Simbaclaws** [comment]
Typescript is telling me allday does not exist on type CalendarOptions...

**Comment by codinronan** [comment]
@Simbaclaws Nope, it is missing from the type declaration, but you can just simply do:

```
calOptions['allday'] = true;
```

and it works just fine.

**Comment by Simbaclaws** [comment]
Thanks a lot @codinronan apparently I need to both set the date and time to 0:00 till 0:00 the next day AND use the allday boolean. When I use both everything seems to work as expected. When I use either it doesn't seem to work...
I've been struggling with this for weeks now. I really appreciate the help everyone has given me 👍

**Comment by Simbaclaws** [comment]
Simply use both the allday boolean AND set the date and time to start date 0:00 and end date the next day 0:00. This issue can be closed.
