### ISSUE TITLE
Event not added in phonegap app in Samsung 6 & 7

### ISSUE THREAD

**Issue by sankari123** [EddyVerbruggen/Calendar-PhoneGap-Plugin#445]
function calAdd()
	
{
	
	calEvt1=calEvt.split('&');
	 calEvtDetails1=calEvtDetails.split('%');
	 
	 
	for (var i = 0; i <calEvt1.length-1; i++) {
 
  var startDate = new Date(calEvt1[i]);
  
  var endDate = new Date(calEvt1[i]);
   
  var title = "Madras Music Miscellany";
  
  var location = "Chennai";
  
  var notes = calEvtDetails1[i];
//		var startDate = new Date(2018,1,15,18,30,0,0,0);  
  //var endDate = new Date(2018,1,15,21,30,0,0,0);
   var calsuccess = function(message) { navigator.notification.alert('Schedule added Successfully...',  alertDismissed,   'Madras Music & Miscellany',   'OK');};
  var calerror = function(message) { alert("Error: " + message); };
 window.plugins.calendar.createEvent(title,location,notes,startDate,endDate,calsuccess,calerror);

	}
   
}	
I am using android galaxy 6 & 7.  The event is not getting added. I tried with static values as well.  Pl help

**Comment by EddyVerbruggen** [comment]
Do not create events in a loop like that, as Cordova is async. Search for similar issues in the repo.

**Comment by sankari123** [comment]
Thanks
