### ISSUE TITLE
Event gets deleted itself in Android Oreo

### ISSUE THREAD

**Issue by sjkushwaha21** [EddyVerbruggen/Calendar-PhoneGap-Plugin#459]
Hi I am trying to mark an appointment into native calendar of the device. This plugin is working fine with all the version of android upto 7.1.1 and iOS 11.2.6 but when i am trying to mark a calendar event in Android Oreo event is being marked but having these following issues:
1. Event is being marked as a birthday rather than the custom title.
2. Event gets deleted itself after 15-25 seconds (Did not check the exact time interval).

Kindly check weather the issue is there or i am the one who is facing it!
Also suggest the proper way to mark it if there is some other steps for Oreo.

Code snap shot is attached.
![screen shot 2018-03-09 at 12 26 39 pm](https://user-images.githubusercontent.com/10279317/37194618-262d6c98-2395-11e8-917a-13c5265ef7c1.png)

**Comment by sjkushwaha21** [comment]
Hi Team,

I am still awaiting response, kindly update me with details??

**Comment by EddyVerbruggen** [comment]
There is no "Team", and I have no idea. Others perhaps?

![strip-vision-open-source-650-finalenglish](https://user-images.githubusercontent.com/1426370/37271503-777d9844-25d3-11e8-9396-1353e4fd2f8b.jpg)

**Comment by sjkushwaha21** [comment]
Hi @EddyVerbruggen I get your point over here, can i please get your help on this?

**Comment by kohlia** [comment]
Hi @EddyVerbruggen can you please fix this as I am too facing the same problem

**Comment by EddyVerbruggen** [comment]
Happy to merge a PR.

**Comment by kohlia** [comment]
I figured it out the calendar ID used is 1 which is birthday calendar for some devices, use 3 in that case

**Comment by kohlia** [comment]
I have created a PR please merge

**Comment by kohlia** [comment]
Can you please merge the PR thank you

**Comment by EddyVerbruggen** [comment]
Thanks for the PR. So `getActiveCalendars` now returns `isPrimary` to indicate whether or not it's the primary calendar.
