### ISSUE TITLE
Excessive wakeups

### ISSUE THREAD

**Issue by edvenkat** [EddyVerbruggen/Calendar-PhoneGap-Plugin#460]
Need help reg Excessive wakeups. please help

**Comment by edvenkat** [comment]
We are using calendar plugin in our android app.
We are tesing In test lab, Excessive wakeups is high.
Please refer the below link
https://developer.android.com/reference/android/app/AlarmManager.html

is the plugin using Alarm Manager for notification?
if not Please tell me what is the concept we are using the save calendar?

**Comment by EddyVerbruggen** [comment]
Tip: use the search box at the top. [A search for `AlarmManager`](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/search?utf8=%E2%9C%93&q=alarmmanager&type=) comes back empty.

You can inspect the code, it's all open source. If it's not to your liking hit the fork button as I'm not deviating from the current implementation.

**Comment by edvenkat** [comment]
did you see the above reference link??
i think, Excessive wakeups occurs due to alarm Manager. Did you use this in plugin?

**Comment by EddyVerbruggen** [comment]
Yes I saw the link regarding AlarmManager and like I said: this plugin doesn’t use it.

**Comment by edvenkat** [comment]
do u have any idea about Excessive wakeups???

Please advice
