### ISSUE TITLE
Android 8.1 (API 27) - Delete causes crash

### ISSUE THREAD

**Issue by nickdeakin** [EddyVerbruggen/Calendar-PhoneGap-Plugin#468]
Executing a delete event produces this error:

>   java.lang.SecurityException: Permission Denial: reading com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/instances/when/1526918400000/1526929200000 from pid=14516, uid=10079 requires android.permission.READ_CALENDAR, or grantUriPermission()
>         at android.os.Parcel.readException(Parcel.java:2004)
>         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
>         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
>         at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
>         at android.content.ContentResolver.query(ContentResolver.java:754)
>         at android.content.ContentResolver.query(ContentResolver.java:704)
>         at android.content.ContentResolver.query(ContentResolver.java:662)
>         at nl.xservices.plugins.accessor.CalendarProviderAccessor.queryEventInstances(CalendarProviderAccessor.java:81)
>         at nl.xservices.plugins.accessor.AbstractCalendarAccessor.fetchEventInstances(AbstractCalendarAccessor.java:216)
>         at nl.xservices.plugins.accessor.AbstractCalendarAccessor.deleteEvent(AbstractCalendarAccessor.java:500)
>         at nl.xservices.plugins.accessor.CalendarProviderAccessor.deleteEvent(CalendarProviderAccessor.java:88)
>         at nl.xservices.plugins.Calendar$7.run(Calendar.java:451)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

I found that adding the following to 
_ Calendar.java
__ deleteEvent(JSONArray args)
___ underneath the check for WRITE_CALENDAR check solves it:
fixes the issue

```
    if (!calendarPermissionGranted(Manifest.permission.READ_CALENDAR)) {
      requestReadPermission(PERMISSION_REQCODE_DELETE_EVENT);
      return;
    }
```

Nick

**Comment by rdantonio** [comment]
We also experienced this issue. I created a pull request with our fix (similar to yours), though I can modify it if needed if someone sees any issues with it.

**Comment by EddyVerbruggen** [comment]
Awesome!
