### ISSUE TITLE
Events disappear on android 8.0 and higher

### ISSUE THREAD

**Issue by ellyverbraeken** [EddyVerbruggen/Calendar-PhoneGap-Plugin#477]
Hi

I updated my cordova app for target 26. However: events are created on the android calendar, but after about 30 seconds you can see the events disappear? Anybody any idea?
This happens only with phones on android 8.0 and higher. (just tested with pixel 2 - 8.1.x)

**Comment by ahmedb49** [comment]
Same issue here
I saw the events was created like "Birthdays" on google calendar and not like "Reminders" and after seconds the events disappear
Help please

**Comment by ellyverbraeken** [comment]
Solved it. They were created on a not primary calendar, so you need to check with listCalendars wich one is the primary one

**Comment by ahmedb49** [comment]
@ellyverbraeken can you please describe more
(some code ...)
