### ISSUE TITLE
createEventInteractivelyWithOptions doesnt consider option "allday"

### ISSUE THREAD

**Issue by nfode** [EddyVerbruggen/Calendar-PhoneGap-Plugin#486]
If I set the calendar option _allday_ it does not get recognized since the `createEventInteractively` Android function calculates if an event is all day by start and end date. 

My question if it would be in your interest to add the feature that the `createEventInteractively` first checks if the option "allday" is set and if not calculates the date.

If it is in your interest I would add an PR.

**Comment by EddyVerbruggen** [comment]
Sounds good!
