### ISSUE TITLE
findEvent and deleteEventById dont work unless followed by alert()

### ISSUE THREAD

**Issue by mill-j** [EddyVerbruggen/Calendar-PhoneGap-Plugin#489]
Hello, I have a problem that might be a JS problem but here goes.

If I call the following function, it works perfectly. However if I remove the Called 4 alert(), calling the function will show Called 1, and does nothing else. What am I overlooking? 

function DelEventInCal(title, notes, d) {
	SDate = new Date(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(),8,0,0,0,0);
	EDate = new Date(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(),8,0,0,0,0);
	
	//Find ID
	alert("called 1");
	window.plugins.calendar.findEvent(title, "Location", notes, SDate, EDate,function(msg) {
		alert("called 2");
		for(var a = 0; a < msg.length; a++) {
			if(msg[a].title == title && msg[a].message == notes) {
				window.plugins.calendar.deleteEventById(msg[a].id, SDate,function() {alert("called 3");},function (msg) {
					alert("Error: " + msg);
				});
			}
		}
	},
	function (msg) {
		alert("error: " + msg);
	});
	alert("Called 4");//debug
}

Thanks

**Comment by thedewi** [comment]
That is certainly a weird one. It sounds a little bit like you could have code tying up the thread so that it never reaches the top of the stack to service callbacks, but `alert()` normally makes that situation worse, not better.

**Comment by mill-j** [comment]
I think you are correct though. I was calling that function and right after it I called a function that created another event. I was able to fix my problem by creating the event inside the deleteByID success function instead of a seperate function.

Thanks!
