### ISSUE TITLE
findAllEventsInNamedCalendar does not load past events

### ISSUE THREAD

**Issue by BennoStaub** [EddyVerbruggen/Calendar-PhoneGap-Plugin#535]
Hey there @EddyVerbruggen and thanks for this plugin!

After googling a lot, I try to get some help here as it should be a minor issue for someone experienced. :)

Calling the function findAllEventsInNamedCalendar on ios does not load any past events, so if it is 10pm it won't show me any events from today before 10pm. 

Is there a way to load also past events, maybe up to one year ago? Like for android where we can input a start and end date. 

thanks a lot for your help!

**Comment by nathantaal** [comment]
@BennoStaub there is a way, listEventsInRange also works on ios :)

**Comment by BennoStaub** [comment]
> 
> 
> @BennoStaub there is a way, listEventsInRange also works on ios :)

Damn, thank you very much lol, it said on the Readme that it is only for android supported so far (at least at some place), now I checked and you are right, my bad! :D 

I already wanted to change the source code in Swift but this makes it way easier :)
