### ISSUE TITLE
All days events are one day late on Android

### ISSUE THREAD

**Issue by pcase** [EddyVerbruggen/Calendar-PhoneGap-Plugin#55]
On my HTC One running Kit Kat, my all day events are displaying one day late on the calendar.  I noticed in the code for AbstractCalendarAccessor.createEvent(), if it is an all day event, one day is added to the start date.  What is the reason for this?

**Comment by cgwyllie** [comment]
+1 Seeing this problem... Any workarounds/fixes for this?

**Comment by EddyVerbruggen** [comment]
Hmm, tried this again and it worked fine on my KitKat device. Perhaps we're passing different things to the plugin? This is what I do to make an all day event for today, so you can compare:
```js
  var startDate = new Date();
  var endDate = new Date();
  endDate.setDate(endDate.getDate()+1);
  // make sure you set these to 0 !
  startDate.setHours(0);
  endDate.setHours(0);
  startDate.setMinutes(0);
  endDate.setMinutes(0);
  startDate.setSeconds(0);
  endDate.setSeconds(0);
  window.plugins.calendar.createEvent('test', 'loc', 'note', startDate, endDate, onSuccess, onError);
```

**Comment by cgwyllie** [comment]
@EddyVerbruggen Hey, thanks for looking at this..

Sadly I'm still seeing this issue in our app.

Our test device is running Android 5.0.0. Could it be related?

Also, perhaps it's to do with the date we're specifying, we're trying to add 2015-01-01 as an all day event.

Thanks

**Comment by EddyVerbruggen** [comment]
What happens if you try my code sample?
