### ISSUE TITLE
Crash IOS 15.1 when creating event

### ISSUE THREAD

**Issue by royvangeel** [EddyVerbruggen/Calendar-PhoneGap-Plugin#554]
Hi, when calling $cordovaCalendar.createEventInteractively on IOS 15.1 our app is crashing. On 15.0 it's working as expected. Is there a known issue for this IOS version?

Error: Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread

**Comment by pendelru** [comment]
We have the same issue here. Any ideas on how to solve this problem?

**Comment by btate** [comment]
Is there a timeline for merging this PR?

**Comment by bbialas** [comment]
+1

**Comment by delitamakanda** [comment]
I am facing the same behavior

**Comment by xinfengmich** [comment]
+1

**Comment by naqeeb-klabs** [comment]
+1

**Comment by ahdaleen** [comment]
+1

**Comment by B4RteQPl** [comment]
+1

**Comment by mwattsED** [comment]
When will this be pushed for release? The last release was in October? Thanks

**Comment by saggio89** [comment]
+1
