### ISSUE TITLE
some questions want to ask you

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Calendar-PhoneGap-Plugin#82]
I am using PGB 3.4 and your latest plugin 4.2.4
Android 4.0.3 and iOS 7.1.2

[question 1]
if I use...
```
window.plugins.calendar.createEventWithOptions(...calOptions,...)
calOptions.firstReminderMinutes = 120;
calOptions.secondReminderMinutes = 5;
```
in Android 4.0.3，it will use the secondReminderMinutes's value as the only Reminder time
but in iOS，it will show two Reminder time exactly
is it because that Android system only have one Reminder time in it's system ?

[issue 1]
I have a data already save in the calendar（the startDate and endDate is really as same as below），Android 4.0.3
```
var startDate = new Date(2014,6,7,18,30,0,0,0);
var endDate = new Date(2014,6,7,19,30,0,0,0);
window.plugins.calendar.listEventsInRange(startDate, endDate, success, error);
```
well..no mater the startDate and endDate are right or wrong that I execute it but seem always trigger the success callback and return an "empty" array

[issue 2]
I have a calendar named "my calendar"，and this calendar have many events
```
var calendarName = "my calendar";
window.plugins.calendar.findAllEventsInNamedCalendar(calendarName, success, error);
```
well..I execute it and trigger the success callback but return an "empty" array，is that a correct behavior ?

[issue 3]
I use..
```
window.plugins.calendar.createEvent(title, location, notes, startDate, endDate, success, error);
```
and it will show a event that I made it in my calendar
finally I use...
```
window.plugins.calendar.deleteEvent(title, location, notes, startDate, endDate, success, error);
```
so the event will be delete indeed
but..
if the event is create by..
```
window.plugins.calendar.createEventWithOptions
window.plugins.calendar.createEventInNamedCalendar
```
above event are all create event successfully too
finally I use...
```
window.plugins.calendar.deleteEvent(title, location, notes, startDate, endDate, success, error);
```
but the event will not delete

well..I guess...is it because that deleteEvent is delete a data in the universal calendar，if a data is save in a Specify Calendar，it will not delete，and "deleteEvent" have no attribute "CalendarName" to point this where to delete

**Comment by bau720123** [comment]
hi @samedii 
just want to ask...
if anything update ?
whatever...any news please let me know

**Comment by samedii** [comment]
@bau720123 the iOS version is working really well (in production too) at least with the functions that I use. Android is almost there but it's on another branch at the moment. Can't say how long it will be before I merge the android stuff, I want it clean up the code more first

**Comment by bau720123** [comment]
hi @samedii 
thanks for your reply
well...
waiting for your good news~

**Comment by bau720123** [comment]
hi @EddyVerbruggen or @samedii 
feedback some information in 4.3.0 version
http://plugins.telerik.com/plugin/calendar

the above question or issues sill exist
and that I found，when I use...
window.plugins.calendar.openCalendar
it perfectly work in android and ios
but Especially in Android 4.0.X
it can't really "locate" the right date

for example
```
var futureDate = new Date(new Date().getTime() + 6*24*60*60*1000); //suppose today is 2015-03-18
window.plugins.calendar.openCalendar(futureDate, success, error);
```
it should be locate to "2015-03-24" but still display "2015-03-18"

**Comment by samedii** [comment]
@bau720123 You should try splitting this issue into several smaller ones and I think you will have a better chance of getting help. You could also try stackoverflow which is more appropriate for questions in general

Also, I think the code you posted last should work and your problem is most likely elsewhere

**Comment by bau720123** [comment]
ok...
thanks @samedii
