### ISSUE TITLE
Bug in Recurrence Event

### ISSUE THREAD

**Issue by rAbdelHadi** [EddyVerbruggen/Calendar-PhoneGap-Plugin#89]
Please test this code on your android device , it will return an error message after a while and if you check your calender you will notice that the event repeated only for 3 months and not for whole period , Thank you .

var startDate = new Date(2014, 5, 16, 18, 30, 0, 0, 0); // beware: month 0 = january, 11 = december
            var endDate = new Date(2014, 5, 19, 19, 30, 0, 0, 0);
	 var calOptions = window.plugins.calendar.getCalendarOptions();
	calOptions.recurrence = "monthly"; // supported are: daily, weekly, monthly, yearly
          calOptions.recurrenceEndDate = new Date(2015,6,1,0,0,0,0,0); // leave null to add events into infinity and beyond
            var title = "My nice event";
            var location = "Home";
            var notes = "Some notes about this event.";
            var success = function (message) { alert("Success: " + JSON.stringify(message)); };
            var error = function (message) { alert("Error: " + message); };
            var calendarName = "Test Calendar";
            alert("Add To Calendar");
  window.plugins.calendar.createEventWithOptions(title,location,notes,startDate,endDate,calOptions,success,error);
            alert("Added");

**Comment by raoulcimpean** [comment]
I have same problem.. have you solved this ?

**Comment by EddyVerbruggen** [comment]
It may be due to the way the recurrence enddate was formatted in the Android code. I just pushed a change.. are you able to test it perhaps?
