### ISSUE TITLE
window.plugins undefined

### ISSUE THREAD

**Issue by bentaly** [EddyVerbruggen/Calendar-PhoneGap-Plugin#95]
Hi,

I am using ionic and want to save events to the native calendar.

Firstly, can this be done with your plugin? I'm under the assumption it can. if not, let me know and read no further.

I added your plugin on the command line with
ionic plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git

and then in my app call
var cal = window.plugins.calendar;
cal.createEventInteractively(title, location, notes, start, end, onSuccess, onError);

In the browser (which is the only place I can debug) window.plugins is undefined.

On the device it seems nothing happens.

Any idea what might be the issue?

Sorry to bother you, any help would be appreciated.

Ben

**Comment by GSD-Automatisering** [comment]
I have a problem on IOS no errors no succes all methods have been recognized but no items in calendar does someone have an idea ?

**Comment by bentaly** [comment]
is it in the:
$window.document.addEventListener('deviceready', function(){});
method?

**Comment by GSD-Automatisering** [comment]
No its after Deviceready has been fired android version works well

**Comment by Junijoh** [comment]
Has anyone resolved the issue?

**Comment by pointer** [comment]
Anyone??

**Comment by thien1590** [comment]
am here too soon :(

**Comment by Marcel-Bich** [comment]
Have you tried the following in your index.html?
In some of my phonegap apps this helped out:
```
window.onload = function() {
	app.initialize()
}
```

**Comment by pointer** [comment]
Will do.... thanks

**Comment by pumpkin-zbh** [comment]
(window as any).cordova.plugins.[pluginName]
