### ISSUE TITLE
findEvent - passing startDate and endDate null or empty

### ISSUE THREAD

**Issue by Krysisx** [EddyVerbruggen/Calendar-PhoneGap-Plugin#97]
Hi,

I need to use the `window.plugins.calendar.findEvent` function passing `null` or `""` to `startDate` and `endDate`. I tried to do that, but it does not work as expected.
So why does `window.plugins.calendar.deleteEvent` work passing `null` to `startDate`, `endDate` but it does not with `window.plugins.calendar.findEvent`?

Thanks

**Comment by junedlanja** [comment]
@Krysisx  reason behind it is in calender.java event are retrieved using following query
 
 //actual query
 Cursor cursor = contentResolver.query(l_eventUri, l_projection, "( dtstart >" + calendar_start.getTimeInMillis() + " AND dtend <" + calendar_end.getTimeInMillis() + " AND deleted = 0)", null, "dtstart ASC");

So if you will not pass start date and end date condition will not satisfied and answer will be different .
So either pass start date and end date or make change in that condition.

@EddyVerbruggen  am i right?

**Comment by EddyVerbruggen** [comment]
@junedlanja yes you are (assuming @Krysisx referred to Android).
